<?php

namespace App\Consts;

class AvailableServiceType
{

    const IMMATRICULATION = "IMMATRICULATION";
    const IMMATRICULATION_STANDARD = "IMMATRICULATION_STANDARD";
    const IMMATRICULATION_PRESTIGE_LABEL = "IMMATRICULATION_PRESTIGE_LABEL";
    const IMMATRICULATION_PRESTIGE_NUMBER = "IMMATRICULATION_PRESTIGE_NUMBER";
    const IMMATRICULATION_PRESTIGE_NUMBER_LABEL = "IMMATRICULATION_PRESTIGE_NUMBER_LABEL";
    const MUTATION = "MUTATION";
    const TITLE_DEPOSIT_OR_RECOVERY = "TITLE_DEPOSIT_OR_RECOVERY";
    const SALE_DECLARATION = "SALE_DECLARATION";
    const TITLE_DEPOSIT = "TITLE_DEPOSIT";
    const TITLE_RECOVERY = "TITLE_RECOVERY";
    const TINTED_WINDOW_AUTHORIZATION= "TINTED_WINDOW_AUTHORIZATION";
    const RE_IMMATRICULATION = "RE_IMMATRICULATION";
    const PLATE_TRANSFORMATION = "PLATE_TRANSFORMATION";
    const PLATE_DUPLICATE = "PLATE_DUPLICATE";
    const GRAY_CARD_DUPLICATE = "GRAY_CARD_DUPLICATE";
    const VEHICLE_TRANSFORMATION = "VEHICLE_TRANSFORMATION";
    const GLASS_ENGRAVING = "GLASS_ENGRAVING";
}
