/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/accreditations/AccreditationCreate': RouteRecordInfo<'/accreditations/AccreditationCreate', '/accreditations/AccreditationCreate', Record<never, never>, Record<never, never>>,
    '/accreditations/AccreditationsList': RouteRecordInfo<'/accreditations/AccreditationsList', '/accreditations/AccreditationsList', Record<never, never>, Record<never, never>>,
    '/accreditations/AccreditationView': RouteRecordInfo<'/accreditations/AccreditationView', '/accreditations/AccreditationView', Record<never, never>, Record<never, never>>,
    '/accreditations/steps/PermissionList': RouteRecordInfo<'/accreditations/steps/PermissionList', '/accreditations/steps/PermissionList', Record<never, never>, Record<never, never>>,
    '/accreditations/steps/ProfileTypeList': RouteRecordInfo<'/accreditations/steps/ProfileTypeList', '/accreditations/steps/ProfileTypeList', Record<never, never>, Record<never, never>>,
    '/accreditations/steps/RoleListe': RouteRecordInfo<'/accreditations/steps/RoleListe', '/accreditations/steps/RoleListe', Record<never, never>, Record<never, never>>,
    '/accreditations/steps/SearchProfile': RouteRecordInfo<'/accreditations/steps/SearchProfile', '/accreditations/steps/SearchProfile', Record<never, never>, Record<never, never>>,
    '/activity-logs/BackButton': RouteRecordInfo<'/activity-logs/BackButton', '/activity-logs/BackButton', Record<never, never>, Record<never, never>>,
    '/activity-logs/LogsList': RouteRecordInfo<'/activity-logs/LogsList', '/activity-logs/LogsList', Record<never, never>, Record<never, never>>,
    '/activity-logs/LogView': RouteRecordInfo<'/activity-logs/LogView', '/activity-logs/LogView', Record<never, never>, Record<never, never>>,
    '/affiliate/affiliate-registration-requests/AffiliateRegistrationRequestCreate': RouteRecordInfo<'/affiliate/affiliate-registration-requests/AffiliateRegistrationRequestCreate', '/affiliate/affiliate-registration-requests/AffiliateRegistrationRequestCreate', Record<never, never>, Record<never, never>>,
    '/affiliate/affiliate-registration-requests/AffiliateRegistrationRequestIndex': RouteRecordInfo<'/affiliate/affiliate-registration-requests/AffiliateRegistrationRequestIndex', '/affiliate/affiliate-registration-requests/AffiliateRegistrationRequestIndex', Record<never, never>, Record<never, never>>,
    '/affiliate/affiliate-registration-requests/AffiliateRegistrationRequestShow': RouteRecordInfo<'/affiliate/affiliate-registration-requests/AffiliateRegistrationRequestShow', '/affiliate/affiliate-registration-requests/AffiliateRegistrationRequestShow', Record<never, never>, Record<never, never>>,
    '/affiliate/affiliate-staff/AffiliateStaffIndex': RouteRecordInfo<'/affiliate/affiliate-staff/AffiliateStaffIndex', '/affiliate/affiliate-staff/AffiliateStaffIndex', Record<never, never>, Record<never, never>>,
    '/affiliate/affiliate-staff/views/EmployeesView': RouteRecordInfo<'/affiliate/affiliate-staff/views/EmployeesView', '/affiliate/affiliate-staff/views/EmployeesView', Record<never, never>, Record<never, never>>,
    '/affiliate/affiliate-staff/views/LeadersView': RouteRecordInfo<'/affiliate/affiliate-staff/views/LeadersView', '/affiliate/affiliate-staff/views/LeadersView', Record<never, never>, Record<never, never>>,
    '/affiliate/affiliates/AffiliateIndex': RouteRecordInfo<'/affiliate/affiliates/AffiliateIndex', '/affiliate/affiliates/AffiliateIndex', Record<never, never>, Record<never, never>>,
    '/affiliate/affiliates/AffiliateShow': RouteRecordInfo<'/affiliate/affiliates/AffiliateShow', '/affiliate/affiliates/AffiliateShow', Record<never, never>, Record<never, never>>,
    '/affiliate/affiliates/tabs/InformationView': RouteRecordInfo<'/affiliate/affiliates/tabs/InformationView', '/affiliate/affiliates/tabs/InformationView', Record<never, never>, Record<never, never>>,
    '/affiliate/affiliates/tabs/LeaderView': RouteRecordInfo<'/affiliate/affiliates/tabs/LeaderView', '/affiliate/affiliates/tabs/LeaderView', Record<never, never>, Record<never, never>>,
    '/affiliate/affiliates/tabs/MemberView': RouteRecordInfo<'/affiliate/affiliates/tabs/MemberView', '/affiliate/affiliates/tabs/MemberView', Record<never, never>, Record<never, never>>,
    '/aggregators/AggregatorCreate': RouteRecordInfo<'/aggregators/AggregatorCreate', '/aggregators/AggregatorCreate', Record<never, never>, Record<never, never>>,
    '/aggregators/AggregatorEdit': RouteRecordInfo<'/aggregators/AggregatorEdit', '/aggregators/AggregatorEdit', Record<never, never>, Record<never, never>>,
    '/aggregators/AggregatorIndex': RouteRecordInfo<'/aggregators/AggregatorIndex', '/aggregators/AggregatorIndex', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/signup': RouteRecordInfo<'/auth/signup', '/auth/signup', Record<never, never>, Record<never, never>>,
    '/BlacklistIndex': RouteRecordInfo<'/BlacklistIndex', '/BlacklistIndex', Record<never, never>, Record<never, never>>,
    '/config/affiliate-categories/AffiliateCategoryCreate': RouteRecordInfo<'/config/affiliate-categories/AffiliateCategoryCreate', '/config/affiliate-categories/AffiliateCategoryCreate', Record<never, never>, Record<never, never>>,
    '/config/affiliate-categories/AffiliateCategoryIndex': RouteRecordInfo<'/config/affiliate-categories/AffiliateCategoryIndex', '/config/affiliate-categories/AffiliateCategoryIndex', Record<never, never>, Record<never, never>>,
    '/config/alert-type/AlertTypeCreate': RouteRecordInfo<'/config/alert-type/AlertTypeCreate', '/config/alert-type/AlertTypeCreate', Record<never, never>, Record<never, never>>,
    '/config/alert-type/AlertTypeIndex': RouteRecordInfo<'/config/alert-type/AlertTypeIndex', '/config/alert-type/AlertTypeIndex', Record<never, never>, Record<never, never>>,
    '/config/anatt-service-types/AnattServiceTypeCreate': RouteRecordInfo<'/config/anatt-service-types/AnattServiceTypeCreate', '/config/anatt-service-types/AnattServiceTypeCreate', Record<never, never>, Record<never, never>>,
    '/config/anatt-service-types/AnattServiceTypeIndex': RouteRecordInfo<'/config/anatt-service-types/AnattServiceTypeIndex', '/config/anatt-service-types/AnattServiceTypeIndex', Record<never, never>, Record<never, never>>,
    '/config/DocumentTypeIndex': RouteRecordInfo<'/config/DocumentTypeIndex', '/config/DocumentTypeIndex', Record<never, never>, Record<never, never>>,
    '/config/frontieres/FrontiereEdit': RouteRecordInfo<'/config/frontieres/FrontiereEdit', '/config/frontieres/FrontiereEdit', Record<never, never>, Record<never, never>>,
    '/config/frontieres/FrontiereNew': RouteRecordInfo<'/config/frontieres/FrontiereNew', '/config/frontieres/FrontiereNew', Record<never, never>, Record<never, never>>,
    '/config/frontieres/FrontieresIndex': RouteRecordInfo<'/config/frontieres/FrontieresIndex', '/config/frontieres/FrontieresIndex', Record<never, never>, Record<never, never>>,
    '/config/immatriculation_types/ImmatriculationTypesCreation': RouteRecordInfo<'/config/immatriculation_types/ImmatriculationTypesCreation', '/config/immatriculation_types/ImmatriculationTypesCreation', Record<never, never>, Record<never, never>>,
    '/config/immatriculation_types/ImmatriculationTypesIndex': RouteRecordInfo<'/config/immatriculation_types/ImmatriculationTypesIndex', '/config/immatriculation_types/ImmatriculationTypesIndex', Record<never, never>, Record<never, never>>,
    '/config/immatriculation_types/ImmatriculationTypesShow': RouteRecordInfo<'/config/immatriculation_types/ImmatriculationTypesShow', '/config/immatriculation_types/ImmatriculationTypesShow', Record<never, never>, Record<never, never>>,
    '/config/immatriculation-formats/ImmatriculationFormatCreate': RouteRecordInfo<'/config/immatriculation-formats/ImmatriculationFormatCreate', '/config/immatriculation-formats/ImmatriculationFormatCreate', Record<never, never>, Record<never, never>>,
    '/config/immatriculation-formats/ImmatriculationFormatIndex': RouteRecordInfo<'/config/immatriculation-formats/ImmatriculationFormatIndex', '/config/immatriculation-formats/ImmatriculationFormatIndex', Record<never, never>, Record<never, never>>,
    '/config/institutions/InstitutionCreate': RouteRecordInfo<'/config/institutions/InstitutionCreate', '/config/institutions/InstitutionCreate', Record<never, never>, Record<never, never>>,
    '/config/institutions/InstitutionIndex': RouteRecordInfo<'/config/institutions/InstitutionIndex', '/config/institutions/InstitutionIndex', Record<never, never>, Record<never, never>>,
    '/config/InstitutionTypeIndex': RouteRecordInfo<'/config/InstitutionTypeIndex', '/config/InstitutionTypeIndex', Record<never, never>, Record<never, never>>,
    '/config/manage-prices/ManagePrices': RouteRecordInfo<'/config/manage-prices/ManagePrices', '/config/manage-prices/ManagePrices', Record<never, never>, Record<never, never>>,
    '/config/manage-prices/ManagePricesCreate': RouteRecordInfo<'/config/manage-prices/ManagePricesCreate', '/config/manage-prices/ManagePricesCreate', Record<never, never>, Record<never, never>>,
    '/config/manage-prices/ManagePricesDuplicate': RouteRecordInfo<'/config/manage-prices/ManagePricesDuplicate', '/config/manage-prices/ManagePricesDuplicate', Record<never, never>, Record<never, never>>,
    '/config/management-center-type/ManagementCenterTypeCreate': RouteRecordInfo<'/config/management-center-type/ManagementCenterTypeCreate', '/config/management-center-type/ManagementCenterTypeCreate', Record<never, never>, Record<never, never>>,
    '/config/management-center-type/ManagementCenterTypeIndex': RouteRecordInfo<'/config/management-center-type/ManagementCenterTypeIndex', '/config/management-center-type/ManagementCenterTypeIndex', Record<never, never>, Record<never, never>>,
    '/config/management-centers/ManagementCenterCreate': RouteRecordInfo<'/config/management-centers/ManagementCenterCreate', '/config/management-centers/ManagementCenterCreate', Record<never, never>, Record<never, never>>,
    '/config/management-centers/ManagementCenterIndex': RouteRecordInfo<'/config/management-centers/ManagementCenterIndex', '/config/management-centers/ManagementCenterIndex', Record<never, never>, Record<never, never>>,
    '/config/meta-data/MetaDataIndex': RouteRecordInfo<'/config/meta-data/MetaDataIndex', '/config/meta-data/MetaDataIndex', Record<never, never>, Record<never, never>>,
    '/config/number-templates/NumberTemplateCreate': RouteRecordInfo<'/config/number-templates/NumberTemplateCreate', '/config/number-templates/NumberTemplateCreate', Record<never, never>, Record<never, never>>,
    '/config/number-templates/NumberTemplateIndex': RouteRecordInfo<'/config/number-templates/NumberTemplateIndex', '/config/number-templates/NumberTemplateIndex', Record<never, never>, Record<never, never>>,
    '/config/organisations/OrganisationCreate': RouteRecordInfo<'/config/organisations/OrganisationCreate', '/config/organisations/OrganisationCreate', Record<never, never>, Record<never, never>>,
    '/config/organisations/OrganisationIndex': RouteRecordInfo<'/config/organisations/OrganisationIndex', '/config/organisations/OrganisationIndex', Record<never, never>, Record<never, never>>,
    '/config/parcs/ParcsCreate': RouteRecordInfo<'/config/parcs/ParcsCreate', '/config/parcs/ParcsCreate', Record<never, never>, Record<never, never>>,
    '/config/parcs/ParcsEdit': RouteRecordInfo<'/config/parcs/ParcsEdit', '/config/parcs/ParcsEdit', Record<never, never>, Record<never, never>>,
    '/config/parcs/ParcsIndex': RouteRecordInfo<'/config/parcs/ParcsIndex', '/config/parcs/ParcsIndex', Record<never, never>, Record<never, never>>,
    '/config/permissions/PermissionIndex': RouteRecordInfo<'/config/permissions/PermissionIndex', '/config/permissions/PermissionIndex', Record<never, never>, Record<never, never>>,
    '/config/plate-colors/PlateColorCreate': RouteRecordInfo<'/config/plate-colors/PlateColorCreate', '/config/plate-colors/PlateColorCreate', Record<never, never>, Record<never, never>>,
    '/config/plate-colors/PlateColorIndex': RouteRecordInfo<'/config/plate-colors/PlateColorIndex', '/config/plate-colors/PlateColorIndex', Record<never, never>, Record<never, never>>,
    '/config/plate-shapes/PlateShapeCreate': RouteRecordInfo<'/config/plate-shapes/PlateShapeCreate', '/config/plate-shapes/PlateShapeCreate', Record<never, never>, Record<never, never>>,
    '/config/plate-shapes/PlateShapeIndex': RouteRecordInfo<'/config/plate-shapes/PlateShapeIndex', '/config/plate-shapes/PlateShapeIndex', Record<never, never>, Record<never, never>>,
    '/config/pricing/PricingConfiguration': RouteRecordInfo<'/config/pricing/PricingConfiguration', '/config/pricing/PricingConfiguration', Record<never, never>, Record<never, never>>,
    '/config/pricing/steps/VehicleCaracteristic': RouteRecordInfo<'/config/pricing/steps/VehicleCaracteristic', '/config/pricing/steps/VehicleCaracteristic', Record<never, never>, Record<never, never>>,
    '/config/pricing/steps/VehicleCategory': RouteRecordInfo<'/config/pricing/steps/VehicleCategory', '/config/pricing/steps/VehicleCategory', Record<never, never>, Record<never, never>>,
    '/config/pricing/steps/VehicleOwnerType': RouteRecordInfo<'/config/pricing/steps/VehicleOwnerType', '/config/pricing/steps/VehicleOwnerType', Record<never, never>, Record<never, never>>,
    '/config/reserved-plate-numbers/ReservedPlateNumbersCreation': RouteRecordInfo<'/config/reserved-plate-numbers/ReservedPlateNumbersCreation', '/config/reserved-plate-numbers/ReservedPlateNumbersCreation', Record<never, never>, Record<never, never>>,
    '/config/reserved-plate-numbers/ReservedPlateNumbersIndex': RouteRecordInfo<'/config/reserved-plate-numbers/ReservedPlateNumbersIndex', '/config/reserved-plate-numbers/ReservedPlateNumbersIndex', Record<never, never>, Record<never, never>>,
    '/config/reserved-plate-numbers/ReservedPlateNumbersShow': RouteRecordInfo<'/config/reserved-plate-numbers/ReservedPlateNumbersShow', '/config/reserved-plate-numbers/ReservedPlateNumbersShow', Record<never, never>, Record<never, never>>,
    '/config/roles/RoleCreate': RouteRecordInfo<'/config/roles/RoleCreate', '/config/roles/RoleCreate', Record<never, never>, Record<never, never>>,
    '/config/roles/RoleIndex': RouteRecordInfo<'/config/roles/RoleIndex', '/config/roles/RoleIndex', Record<never, never>, Record<never, never>>,
    '/config/services/actions/ActionCreate': RouteRecordInfo<'/config/services/actions/ActionCreate', '/config/services/actions/ActionCreate', Record<never, never>, Record<never, never>>,
    '/config/services/actions/ActionList': RouteRecordInfo<'/config/services/actions/ActionList', '/config/services/actions/ActionList', Record<never, never>, Record<never, never>>,
    '/config/services/actions/ActionView': RouteRecordInfo<'/config/services/actions/ActionView', '/config/services/actions/ActionView', Record<never, never>, Record<never, never>>,
    '/config/services/ServiceCreation': RouteRecordInfo<'/config/services/ServiceCreation', '/config/services/ServiceCreation', Record<never, never>, Record<never, never>>,
    '/config/services/ServiceIndex': RouteRecordInfo<'/config/services/ServiceIndex', '/config/services/ServiceIndex', Record<never, never>, Record<never, never>>,
    '/config/services/ServiceView': RouteRecordInfo<'/config/services/ServiceView', '/config/services/ServiceView', Record<never, never>, Record<never, never>>,
    '/config/services/steps/CustomizationStep': RouteRecordInfo<'/config/services/steps/CustomizationStep', '/config/services/steps/CustomizationStep', Record<never, never>, Record<never, never>>,
    '/config/services/steps/OtherStep': RouteRecordInfo<'/config/services/steps/OtherStep', '/config/services/steps/OtherStep', Record<never, never>, Record<never, never>>,
    '/config/services/steps/ProceduralInfoStep': RouteRecordInfo<'/config/services/steps/ProceduralInfoStep', '/config/services/steps/ProceduralInfoStep', Record<never, never>, Record<never, never>>,
    '/config/services/steps/RelationalInfoStep': RouteRecordInfo<'/config/services/steps/RelationalInfoStep', '/config/services/steps/RelationalInfoStep', Record<never, never>, Record<never, never>>,
    '/config/services/steps/ServiceSteps': RouteRecordInfo<'/config/services/steps/ServiceSteps', '/config/services/steps/ServiceSteps', Record<never, never>, Record<never, never>>,
    '/config/spaces/SpaceList': RouteRecordInfo<'/config/spaces/SpaceList', '/config/spaces/SpaceList', Record<never, never>, Record<never, never>>,
    '/config/spaces/SpaceView': RouteRecordInfo<'/config/spaces/SpaceView', '/config/spaces/SpaceView', Record<never, never>, Record<never, never>>,
    '/config/spaces/SuspensionLiftingModal': RouteRecordInfo<'/config/spaces/SuspensionLiftingModal', '/config/spaces/SuspensionLiftingModal', Record<never, never>, Record<never, never>>,
    '/config/spaces/SuspensionModal': RouteRecordInfo<'/config/spaces/SuspensionModal', '/config/spaces/SuspensionModal', Record<never, never>, Record<never, never>>,
    '/config/spaces/TemplateUpdateForm': RouteRecordInfo<'/config/spaces/TemplateUpdateForm', '/config/spaces/TemplateUpdateForm', Record<never, never>, Record<never, never>>,
    '/config/staff/StaffCreate': RouteRecordInfo<'/config/staff/StaffCreate', '/config/staff/StaffCreate', Record<never, never>, Record<never, never>>,
    '/config/staff/StaffIndex': RouteRecordInfo<'/config/staff/StaffIndex', '/config/staff/StaffIndex', Record<never, never>, Record<never, never>>,
    '/config/staff/StaffShow': RouteRecordInfo<'/config/staff/StaffShow', '/config/staff/StaffShow', Record<never, never>, Record<never, never>>,
    '/config/TitleReasonsIndex': RouteRecordInfo<'/config/TitleReasonsIndex', '/config/TitleReasonsIndex', Record<never, never>, Record<never, never>>,
    '/config/vehicle-brands/VehicleBrandCreate': RouteRecordInfo<'/config/vehicle-brands/VehicleBrandCreate', '/config/vehicle-brands/VehicleBrandCreate', Record<never, never>, Record<never, never>>,
    '/config/vehicle-brands/VehicleBrandIndex': RouteRecordInfo<'/config/vehicle-brands/VehicleBrandIndex', '/config/vehicle-brands/VehicleBrandIndex', Record<never, never>, Record<never, never>>,
    '/config/vehicle-characteristic-categories/VehicleCharacteristicCategoryCreate': RouteRecordInfo<'/config/vehicle-characteristic-categories/VehicleCharacteristicCategoryCreate', '/config/vehicle-characteristic-categories/VehicleCharacteristicCategoryCreate', Record<never, never>, Record<never, never>>,
    '/config/vehicle-characteristic-categories/VehicleCharacteristicCategoryIndex': RouteRecordInfo<'/config/vehicle-characteristic-categories/VehicleCharacteristicCategoryIndex', '/config/vehicle-characteristic-categories/VehicleCharacteristicCategoryIndex', Record<never, never>, Record<never, never>>,
    '/config/vehicle-characteristics/VehicleCharacteristicCreate': RouteRecordInfo<'/config/vehicle-characteristics/VehicleCharacteristicCreate', '/config/vehicle-characteristics/VehicleCharacteristicCreate', Record<never, never>, Record<never, never>>,
    '/config/vehicle-characteristics/VehicleCharacteristicIndex': RouteRecordInfo<'/config/vehicle-characteristics/VehicleCharacteristicIndex', '/config/vehicle-characteristics/VehicleCharacteristicIndex', Record<never, never>, Record<never, never>>,
    '/config/vehicle-energy-sources/EnergySourceCreate': RouteRecordInfo<'/config/vehicle-energy-sources/EnergySourceCreate', '/config/vehicle-energy-sources/EnergySourceCreate', Record<never, never>, Record<never, never>>,
    '/config/vehicle-energy-sources/EnergySourceIndex': RouteRecordInfo<'/config/vehicle-energy-sources/EnergySourceIndex', '/config/vehicle-energy-sources/EnergySourceIndex', Record<never, never>, Record<never, never>>,
    '/config/vehicle-types/VehicleTypeCreate': RouteRecordInfo<'/config/vehicle-types/VehicleTypeCreate', '/config/vehicle-types/VehicleTypeCreate', Record<never, never>, Record<never, never>>,
    '/config/vehicle-types/VehicleTypeIndex': RouteRecordInfo<'/config/vehicle-types/VehicleTypeIndex', '/config/vehicle-types/VehicleTypeIndex', Record<never, never>, Record<never, never>>,
    '/config/VehicleCategoriesIndex': RouteRecordInfo<'/config/VehicleCategoriesIndex', '/config/VehicleCategoriesIndex', Record<never, never>, Record<never, never>>,
    '/config/VehiclePowerIndex': RouteRecordInfo<'/config/VehiclePowerIndex', '/config/VehiclePowerIndex', Record<never, never>, Record<never, never>>,
    '/config/zones/DistrictIndex': RouteRecordInfo<'/config/zones/DistrictIndex', '/config/zones/DistrictIndex', Record<never, never>, Record<never, never>>,
    '/config/zones/TownIndex': RouteRecordInfo<'/config/zones/TownIndex', '/config/zones/TownIndex', Record<never, never>, Record<never, never>>,
    '/config/zones/VillagesIndex': RouteRecordInfo<'/config/zones/VillagesIndex', '/config/zones/VillagesIndex', Record<never, never>, Record<never, never>>,
    '/config/zones/ZoneIndex': RouteRecordInfo<'/config/zones/ZoneIndex', '/config/zones/ZoneIndex', Record<never, never>, Record<never, never>>,
    '/configs': RouteRecordInfo<'/configs', '/configs', Record<never, never>, Record<never, never>>,
    '/demands/Actions/ManagementCenterAssignation': RouteRecordInfo<'/demands/Actions/ManagementCenterAssignation', '/demands/Actions/ManagementCenterAssignation', Record<never, never>, Record<never, never>>,
    '/demands/Actions/PrintOrderValidation': RouteRecordInfo<'/demands/Actions/PrintOrderValidation', '/demands/Actions/PrintOrderValidation', Record<never, never>, Record<never, never>>,
    '/demands/Actions/ServiceAssignation': RouteRecordInfo<'/demands/Actions/ServiceAssignation', '/demands/Actions/ServiceAssignation', Record<never, never>, Record<never, never>>,
    '/demands/Actions/StaffAssignation': RouteRecordInfo<'/demands/Actions/StaffAssignation', '/demands/Actions/StaffAssignation', Record<never, never>, Record<never, never>>,
    '/demands/Actions/ValidateReject': RouteRecordInfo<'/demands/Actions/ValidateReject', '/demands/Actions/ValidateReject', Record<never, never>, Record<never, never>>,
    '/demands/Actions/VerifyReject': RouteRecordInfo<'/demands/Actions/VerifyReject', '/demands/Actions/VerifyReject', Record<never, never>, Record<never, never>>,
    '/demands/Cards/FileList': RouteRecordInfo<'/demands/Cards/FileList', '/demands/Cards/FileList', Record<never, never>, Record<never, never>>,
    '/demands/Cards/GrayCard': RouteRecordInfo<'/demands/Cards/GrayCard', '/demands/Cards/GrayCard', Record<never, never>, Record<never, never>>,
    '/demands/Cards/StatutInfoCard': RouteRecordInfo<'/demands/Cards/StatutInfoCard', '/demands/Cards/StatutInfoCard', Record<never, never>, Record<never, never>>,
    '/demands/Cards/UserInfoCard': RouteRecordInfo<'/demands/Cards/UserInfoCard', '/demands/Cards/UserInfoCard', Record<never, never>, Record<never, never>>,
    '/demands/Cards/VehicleInfoCard': RouteRecordInfo<'/demands/Cards/VehicleInfoCard', '/demands/Cards/VehicleInfoCard', Record<never, never>, Record<never, never>>,
    '/demands/DemandActions': RouteRecordInfo<'/demands/DemandActions', '/demands/DemandActions', Record<never, never>, Record<never, never>>,
    '/demands/DemandsExport': RouteRecordInfo<'/demands/DemandsExport', '/demands/DemandsExport', Record<never, never>, Record<never, never>>,
    '/demands/DemandsList': RouteRecordInfo<'/demands/DemandsList', '/demands/DemandsList', Record<never, never>, Record<never, never>>,
    '/demands/DemandView': RouteRecordInfo<'/demands/DemandView', '/demands/DemandView', Record<never, never>, Record<never, never>>,
    '/demands/Parts/AssignationPart': RouteRecordInfo<'/demands/Parts/AssignationPart', '/demands/Parts/AssignationPart', Record<never, never>, Record<never, never>>,
    '/demands/Parts/CertificateInfoPart': RouteRecordInfo<'/demands/Parts/CertificateInfoPart', '/demands/Parts/CertificateInfoPart', Record<never, never>, Record<never, never>>,
    '/demands/Parts/DemandInfoPart': RouteRecordInfo<'/demands/Parts/DemandInfoPart', '/demands/Parts/DemandInfoPart', Record<never, never>, Record<never, never>>,
    '/demands/Parts/GrayCardPart': RouteRecordInfo<'/demands/Parts/GrayCardPart', '/demands/Parts/GrayCardPart', Record<never, never>, Record<never, never>>,
    '/demands/Parts/ImmatriculationPart': RouteRecordInfo<'/demands/Parts/ImmatriculationPart', '/demands/Parts/ImmatriculationPart', Record<never, never>, Record<never, never>>,
    '/demands/Parts/ImpressionPart': RouteRecordInfo<'/demands/Parts/ImpressionPart', '/demands/Parts/ImpressionPart', Record<never, never>, Record<never, never>>,
    '/demands/Parts/MutationInfoPart': RouteRecordInfo<'/demands/Parts/MutationInfoPart', '/demands/Parts/MutationInfoPart', Record<never, never>, Record<never, never>>,
    '/demands/Parts/SaleInfoPart': RouteRecordInfo<'/demands/Parts/SaleInfoPart', '/demands/Parts/SaleInfoPart', Record<never, never>, Record<never, never>>,
    '/demands/Parts/TitleInfoPart': RouteRecordInfo<'/demands/Parts/TitleInfoPart', '/demands/Parts/TitleInfoPart', Record<never, never>, Record<never, never>>,
    '/demands/steps/AffectationView': RouteRecordInfo<'/demands/steps/AffectationView', '/demands/steps/AffectationView', Record<never, never>, Record<never, never>>,
    '/demands/steps/BlacklistView': RouteRecordInfo<'/demands/steps/BlacklistView', '/demands/steps/BlacklistView', Record<never, never>, Record<never, never>>,
    '/demands/steps/ControlView': RouteRecordInfo<'/demands/steps/ControlView', '/demands/steps/ControlView', Record<never, never>, Record<never, never>>,
    '/demands/steps/GrayCardView': RouteRecordInfo<'/demands/steps/GrayCardView', '/demands/steps/GrayCardView', Record<never, never>, Record<never, never>>,
    '/demands/steps/ImmatriculationView': RouteRecordInfo<'/demands/steps/ImmatriculationView', '/demands/steps/ImmatriculationView', Record<never, never>, Record<never, never>>,
    '/demands/steps/InterpolView': RouteRecordInfo<'/demands/steps/InterpolView', '/demands/steps/InterpolView', Record<never, never>, Record<never, never>>,
    '/demands/steps/MainView': RouteRecordInfo<'/demands/steps/MainView', '/demands/steps/MainView', Record<never, never>, Record<never, never>>,
    '/demands/steps/PrintView': RouteRecordInfo<'/demands/steps/PrintView', '/demands/steps/PrintView', Record<never, never>, Record<never, never>>,
    '/errors/NotFound': RouteRecordInfo<'/errors/NotFound', '/errors/NotFound', Record<never, never>, Record<never, never>>,
    '/gray-card-demands/GrayCardDemandIndex': RouteRecordInfo<'/gray-card-demands/GrayCardDemandIndex', '/gray-card-demands/GrayCardDemandIndex', Record<never, never>, Record<never, never>>,
    '/gray-card-demands/GrayCardDemandShow': RouteRecordInfo<'/gray-card-demands/GrayCardDemandShow', '/gray-card-demands/GrayCardDemandShow', Record<never, never>, Record<never, never>>,
    '/gray-card-duplicate/GrayCardDuplicateList': RouteRecordInfo<'/gray-card-duplicate/GrayCardDuplicateList', '/gray-card-duplicate/GrayCardDuplicateList', Record<never, never>, Record<never, never>>,
    '/gray-card-duplicate/GrayCardDuplicateShow': RouteRecordInfo<'/gray-card-duplicate/GrayCardDuplicateShow', '/gray-card-duplicate/GrayCardDuplicateShow', Record<never, never>, Record<never, never>>,
    '/gray-card-duplicate/steps/AffectationView': RouteRecordInfo<'/gray-card-duplicate/steps/AffectationView', '/gray-card-duplicate/steps/AffectationView', Record<never, never>, Record<never, never>>,
    '/gray-card-duplicate/steps/GrayCardView': RouteRecordInfo<'/gray-card-duplicate/steps/GrayCardView', '/gray-card-duplicate/steps/GrayCardView', Record<never, never>, Record<never, never>>,
    '/gray-card-duplicate/steps/MainView': RouteRecordInfo<'/gray-card-duplicate/steps/MainView', '/gray-card-duplicate/steps/MainView', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/Opposition/List': RouteRecordInfo<'/Opposition/List', '/Opposition/List', Record<never, never>, Record<never, never>>,
    '/Opposition/Show': RouteRecordInfo<'/Opposition/Show', '/Opposition/Show', Record<never, never>, Record<never, never>>,
    '/orders/Cards/DemandInfoCard': RouteRecordInfo<'/orders/Cards/DemandInfoCard', '/orders/Cards/DemandInfoCard', Record<never, never>, Record<never, never>>,
    '/orders/Cards/OrderInfoCard': RouteRecordInfo<'/orders/Cards/OrderInfoCard', '/orders/Cards/OrderInfoCard', Record<never, never>, Record<never, never>>,
    '/orders/Cards/TransactionInfoCard': RouteRecordInfo<'/orders/Cards/TransactionInfoCard', '/orders/Cards/TransactionInfoCard', Record<never, never>, Record<never, never>>,
    '/orders/OrdersList': RouteRecordInfo<'/orders/OrdersList', '/orders/OrdersList', Record<never, never>, Record<never, never>>,
    '/orders/OrderView': RouteRecordInfo<'/orders/OrderView', '/orders/OrderView', Record<never, never>, Record<never, never>>,
    '/OwnerTypeIndex': RouteRecordInfo<'/OwnerTypeIndex', '/OwnerTypeIndex', Record<never, never>, Record<never, never>>,
    '/plate-duplicate/PlateDuplicateList': RouteRecordInfo<'/plate-duplicate/PlateDuplicateList', '/plate-duplicate/PlateDuplicateList', Record<never, never>, Record<never, never>>,
    '/plate-duplicate/PlateDuplicateShow': RouteRecordInfo<'/plate-duplicate/PlateDuplicateShow', '/plate-duplicate/PlateDuplicateShow', Record<never, never>, Record<never, never>>,
    '/plate-duplicate/steps/AffectationView': RouteRecordInfo<'/plate-duplicate/steps/AffectationView', '/plate-duplicate/steps/AffectationView', Record<never, never>, Record<never, never>>,
    '/plate-duplicate/steps/ImmatriculationView': RouteRecordInfo<'/plate-duplicate/steps/ImmatriculationView', '/plate-duplicate/steps/ImmatriculationView', Record<never, never>, Record<never, never>>,
    '/plate-duplicate/steps/MainView': RouteRecordInfo<'/plate-duplicate/steps/MainView', '/plate-duplicate/steps/MainView', Record<never, never>, Record<never, never>>,
    '/PlateOrders/PlateOrderForm': RouteRecordInfo<'/PlateOrders/PlateOrderForm', '/PlateOrders/PlateOrderForm', Record<never, never>, Record<never, never>>,
    '/PlateOrders/PlateOrderList': RouteRecordInfo<'/PlateOrders/PlateOrderList', '/PlateOrders/PlateOrderList', Record<never, never>, Record<never, never>>,
    '/PlateOrders/PlateOrderShow': RouteRecordInfo<'/PlateOrders/PlateOrderShow', '/PlateOrders/PlateOrderShow', Record<never, never>, Record<never, never>>,
    '/PlateOrders/PlateOrderValidation': RouteRecordInfo<'/PlateOrders/PlateOrderValidation', '/PlateOrders/PlateOrderValidation', Record<never, never>, Record<never, never>>,
    '/Plates/PlateImport': RouteRecordInfo<'/Plates/PlateImport', '/Plates/PlateImport', Record<never, never>, Record<never, never>>,
    '/Plates/PlateList': RouteRecordInfo<'/Plates/PlateList', '/Plates/PlateList', Record<never, never>, Record<never, never>>,
    '/PledgesIssueRequest/List': RouteRecordInfo<'/PledgesIssueRequest/List', '/PledgesIssueRequest/List', Record<never, never>, Record<never, never>>,
    '/PledgesIssueRequest/Show': RouteRecordInfo<'/PledgesIssueRequest/Show', '/PledgesIssueRequest/Show', Record<never, never>, Record<never, never>>,
    '/PledgesLiftIssueRequest/List': RouteRecordInfo<'/PledgesLiftIssueRequest/List', '/PledgesLiftIssueRequest/List', Record<never, never>, Record<never, never>>,
    '/PledgesLiftIssueRequest/Show': RouteRecordInfo<'/PledgesLiftIssueRequest/Show', '/PledgesLiftIssueRequest/Show', Record<never, never>, Record<never, never>>,
    '/PrintOrders/PrintOrderList': RouteRecordInfo<'/PrintOrders/PrintOrderList', '/PrintOrders/PrintOrderList', Record<never, never>, Record<never, never>>,
    '/PrintOrders/PrintOrderShow': RouteRecordInfo<'/PrintOrders/PrintOrderShow', '/PrintOrders/PrintOrderShow', Record<never, never>, Record<never, never>>,
    '/re-immatriculation-demands/ReImmatriculationDemandsIndex': RouteRecordInfo<'/re-immatriculation-demands/ReImmatriculationDemandsIndex', '/re-immatriculation-demands/ReImmatriculationDemandsIndex', Record<never, never>, Record<never, never>>,
    '/re-immatriculation-demands/ReImmatriculationDemandsShow': RouteRecordInfo<'/re-immatriculation-demands/ReImmatriculationDemandsShow', '/re-immatriculation-demands/ReImmatriculationDemandsShow', Record<never, never>, Record<never, never>>,
    '/RequiredDocumentTypeIndex': RouteRecordInfo<'/RequiredDocumentTypeIndex', '/RequiredDocumentTypeIndex', Record<never, never>, Record<never, never>>,
    '/SpacesRegistrationRequest/SpaceRegistrationCreate': RouteRecordInfo<'/SpacesRegistrationRequest/SpaceRegistrationCreate', '/SpacesRegistrationRequest/SpaceRegistrationCreate', Record<never, never>, Record<never, never>>,
    '/SpacesRegistrationRequest/SpaceRegistrationList': RouteRecordInfo<'/SpacesRegistrationRequest/SpaceRegistrationList', '/SpacesRegistrationRequest/SpaceRegistrationList', Record<never, never>, Record<never, never>>,
    '/SpacesRegistrationRequest/SpaceRegistrationShow': RouteRecordInfo<'/SpacesRegistrationRequest/SpaceRegistrationShow', '/SpacesRegistrationRequest/SpaceRegistrationShow', Record<never, never>, Record<never, never>>,
    '/StatCard': RouteRecordInfo<'/StatCard', '/StatCard', Record<never, never>, Record<never, never>>,
    '/taches/DemandsList': RouteRecordInfo<'/taches/DemandsList', '/taches/DemandsList', Record<never, never>, Record<never, never>>,
    '/traitements/DemandsList': RouteRecordInfo<'/traitements/DemandsList', '/traitements/DemandsList', Record<never, never>, Record<never, never>>,
    '/user/tabs/UserActivity': RouteRecordInfo<'/user/tabs/UserActivity', '/user/tabs/UserActivity', Record<never, never>, Record<never, never>>,
    '/user/tabs/UserDemands': RouteRecordInfo<'/user/tabs/UserDemands', '/user/tabs/UserDemands', Record<never, never>, Record<never, never>>,
    '/user/tabs/UserVehicles': RouteRecordInfo<'/user/tabs/UserVehicles', '/user/tabs/UserVehicles', Record<never, never>, Record<never, never>>,
    '/user/UserShow': RouteRecordInfo<'/user/UserShow', '/user/UserShow', Record<never, never>, Record<never, never>>,
    '/vehicles/Cards/FileList': RouteRecordInfo<'/vehicles/Cards/FileList', '/vehicles/Cards/FileList', Record<never, never>, Record<never, never>>,
    '/vehicles/Cards/GrayCard': RouteRecordInfo<'/vehicles/Cards/GrayCard', '/vehicles/Cards/GrayCard', Record<never, never>, Record<never, never>>,
    '/vehicles/Cards/ImmatriculationCard': RouteRecordInfo<'/vehicles/Cards/ImmatriculationCard', '/vehicles/Cards/ImmatriculationCard', Record<never, never>, Record<never, never>>,
    '/vehicles/Cards/InfractionCard': RouteRecordInfo<'/vehicles/Cards/InfractionCard', '/vehicles/Cards/InfractionCard', Record<never, never>, Record<never, never>>,
    '/vehicles/Cards/OwnerInfoCard': RouteRecordInfo<'/vehicles/Cards/OwnerInfoCard', '/vehicles/Cards/OwnerInfoCard', Record<never, never>, Record<never, never>>,
    '/vehicles/Cards/PassageCard': RouteRecordInfo<'/vehicles/Cards/PassageCard', '/vehicles/Cards/PassageCard', Record<never, never>, Record<never, never>>,
    '/vehicles/Cards/RelatedDemands': RouteRecordInfo<'/vehicles/Cards/RelatedDemands', '/vehicles/Cards/RelatedDemands', Record<never, never>, Record<never, never>>,
    '/vehicles/Cards/StatutInfoCard': RouteRecordInfo<'/vehicles/Cards/StatutInfoCard', '/vehicles/Cards/StatutInfoCard', Record<never, never>, Record<never, never>>,
    '/vehicles/Cards/VehicleAssets': RouteRecordInfo<'/vehicles/Cards/VehicleAssets', '/vehicles/Cards/VehicleAssets', Record<never, never>, Record<never, never>>,
    '/vehicles/Cards/VehicleLifecycle': RouteRecordInfo<'/vehicles/Cards/VehicleLifecycle', '/vehicles/Cards/VehicleLifecycle', Record<never, never>, Record<never, never>>,
    '/vehicles/vehicles/VehicleSearch': RouteRecordInfo<'/vehicles/vehicles/VehicleSearch', '/vehicles/vehicles/VehicleSearch', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
