<?php


namespace Database\Seeders\Config;

use App\Consts\NotificationNames;
use App\Models\Config\NotificationConfig;
use Database\Seeders\Notifications\Duplicate;
use Illuminate\Database\Seeder;

class NotificationConfigSeeder extends Seeder
{
    public function __construct()
    {
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $notificationConfigs = [
            'PlateColorChangeApplicationSubmittedSuccessfully' => [
                'name' => 'plate-color-change-application-submitted-successfully',
                'title' => 'Dossier soumis',
                'message_sms' => 'Votre dossier de changement de la couleur de votre plaque d\'immatriculation a ete soumis avec succes.',
                'message_in_app' => 'Votre dossier de changement de la couleur de votre plaque d\'immatriculation a ete soumis avec succes.',
                'message_mail' => 'Votre dossier de changement de la couleur de votre plaque d\'immatriculation a ete soumis avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateColorChangeApplicationUnderReview' => [
                'name' => 'plate-color-change-application-under-review',
                'title' => 'Examen de dossier en cours',
                'message_sms' => 'Votre dossier de changement de la couleur de votre plaque d\'immatriculation est en cours d\'examen.',
                'message_in_app' => 'Votre dossier de changement de la couleur de votre plaque d\'immatriculation est en cours d\'examen.',
                'message_mail' => 'Votre dossier de changement de la couleur de votre plaque d\'immatriculation est en cours d\'examen.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateColorChangeApproved' => [
                'name' => 'plate-color-change-approved',
                'title' => 'Demande approuvee',
                'message_sms' => 'Votre demande de changement de la couleur de votre plaque d\'immatriculation a ete approuvee.',
                'message_in_app' => 'Votre demande de changement de la couleur de votre plaque d\'immatriculation a ete approuvee.',
                'message_mail' => 'Votre demande de changement de la couleur de votre plaque d\'immatriculation a ete approuvee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateColorChangeRejected' => [
                'name' => 'plate-color-change-rejected',
                'title' => 'Demande rejetee',
                'message_sms' => 'Votre demande de changement de la couleur de votre plaque d\'immatriculation a ete rejetee.',
                'message_in_app' => 'Votre demande de changement de la couleur de votre plaque d\'immatriculation a ete rejetee.',
                'message_mail' => 'Votre demande de changement de la couleur de votre plaque d\'immatriculation a ete rejetee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateColorChangePaymentSuccessful' => [
                'name' => 'plate-color-change-payment-successful',
                'title' => 'Paiement reussi',
                'message_sms' => 'Le paiement pour le changement de la couleur de votre plaque d\'immatriculation a ete effectue avec succes.',
                'message_in_app' => 'Le paiement pour le changement de la couleur de votre plaque d\'immatriculation a ete effectue avec succes.',
                'message_mail' => 'Le paiement pour le changement de la couleur de votre plaque d\'immatriculation a ete effectue avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateColorChangePaymentError' => [
                'name' => 'plate-color-change-payment-error',
                'title' => 'Echec du paiement',
                'message_sms' => 'Le paiement pour le changement de la couleur de votre plaque d\'immatriculation a echoue. Veuillez reessayer.',
                'message_in_app' => 'Le paiement pour le changement de la couleur de votre plaque d\'immatriculation a echoue. Veuillez reessayer.',
                'message_mail' => 'Le paiement pour le changement de la couleur de votre plaque d\'immatriculation a echoue. Veuillez reessayer.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateColorChangeOngoing' => [
                'name' => 'plate-color-change-ongoing',
                'title' => 'Changement de couleur de plaque d\'immatriculation en cours',
                'message_sms' => 'Le changement de la couleur de votre plaque d\'immatriculation est en cours.',
                'message_in_app' => 'Le changement de la couleur de votre plaque d\'immatriculation est en cours.',
                'message_mail' => 'Le changement de la couleur de votre plaque d\'immatriculation est en cours.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateColorChangeSuccessful' => [
                'name' => 'plate-color-change-successful',
                'title' => 'Changement de couleur de plaque d\'immatriculation effectue avec succes',
                'message_sms' => 'Le changement de la couleur de votre plaque d\'immatriculation a ete effectue avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_in_app' => 'Le changement de la couleur de votre plaque d\'immatriculation a ete effectue avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_mail' => 'Le changement de la couleur de votre plaque d\'immatriculation a ete effectue avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleWithdrawalApplicationSubmittedSuccessfully' => [
                'name' => 'vehicle-withdrawal-application-submitted-successfully',
                'title' => 'Dossier soumis',
                'message_sms' => 'Votre dossier de retrait de votre vehicule de la circulation a ete soumis avec succes.',
                'message_in_app' => 'Votre dossier de retrait de votre vehicule de la circulation a ete soumis avec succes.',
                'message_mail' => 'Votre dossier de retrait de votre vehicule de la circulation a ete soumis avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleWithdrawalApplicationUnderReview' => [
                'name' => 'vehicle-withdrawal-application-under-review',
                'title' => 'Examen de dossier en cours',
                'message_sms' => 'Le dossier de retrait de votre vehicule de la circulation est en cours d\'examen.',
                'message_in_app' => 'Le dossier de retrait de votre vehicule de la circulation est en cours d\'examen.',
                'message_mail' => 'Le dossier de retrait de votre vehicule de la circulation est en cours d\'examen.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleWithdrawalApproved' => [
                'name' => 'vehicle-withdrawal-approved',
                'title' => 'Demande approuvee',
                'message_sms' => 'La demande de retrait de votre vehicule de la circulation a ete approuvee.',
                'message_in_app' => 'La demande de retrait de votre vehicule de la circulation a ete approuvee.',
                'message_mail' => 'La demande de retrait de votre vehicule de la circulation a ete approuvee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleWithdrawalRejected' => [
                'name' => 'vehicle-withdrawal-rejected',
                'title' => 'Demande rejetee',
                'message_sms' => 'La demande de retrait de votre vehicule de la circulation a ete rejetee.',
                'message_in_app' => 'La demande de retrait de votre vehicule de la circulation a ete rejetee.',
                'message_mail' => 'La demande de retrait de votre vehicule de la circulation a ete rejetee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleWithdrawalPaymentSuccessful' => [
                'name' => 'vehicle-withdrawal-payment-successful',
                'title' => 'Paiement reussi',
                'message_sms' => 'Le paiement pour le retrait de votre vehicule de la circulation a ete effectue avec succes.',
                'message_in_app' => 'Le paiement pour le retrait de votre vehicule de la circulation a ete effectue avec succes.',
                'message_mail' => 'Le paiement pour le retrait de votre vehicule de la circulation a ete effectue avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleWithdrawalPaymentError' => [
                'name' => 'vehicle-withdrawal-payment-error',
                'title' => 'Echec du paiement',
                'message_sms' => 'Le paiement pour le retrait de votre vehicule de la circulation a echoue. Veuillez reessayer.',
                'message_in_app' => 'Le paiement pour le retrait de votre vehicule de la circulation a echoue. Veuillez reessayer.',
                'message_mail' => 'Le paiement pour le retrait de votre vehicule de la circulation a echoue. Veuillez reessayer.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleWithdrawalOngoing' => [
                'name' => 'vehicle-withdrawal-ongoing',
                'title' => 'Retrait de vehicule en cours',
                'message_sms' => 'Le retrait de votre vehicule de la circulation est en cours.',
                'message_in_app' => 'Le retrait de votre vehicule de la circulation est en cours.',
                'message_mail' => 'Le retrait de votre vehicule de la circulation est en cours.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleWithdrawalSuccessful' => [
                'name' => 'vehicle-withdrawal-successful',
                'title' => 'Retrait de vehicule effectue avec succes',
                'message_sms' => 'Le retrait de votre vehicule de la circulation a ete effectue avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_in_app' => 'Le retrait de votre vehicule de la circulation a ete effectue avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_mail' => 'Le retrait de votre vehicule de la circulation a ete effectue avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleReuseApplicationSubmittedSuccessfully' => [
                'name' => 'vehicle-reuse-application-submitted-successfully',
                'title' => 'Dossier soumis',
                'message_sms' => 'Votre dossier de remise en circulation de votre vehicule a ete soumis avec succes.',
                'message_in_app' => 'Votre dossier de remise en circulation de votre vehicule a ete soumis avec succes.',
                'message_mail' => 'Votre dossier de remise en circulation de votre vehicule a ete soumis avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleReuseApplicationUnderReview' => [
                'name' => 'vehicle-reuse-application-under-review',
                'title' => 'Examen de dossier en cours',
                'message_sms' => 'Le dossier de remise en circulation de votre vehicule est en cours d\'examen.',
                'message_in_app' => 'Le dossier de remise en circulation de votre vehicule est en cours d\'examen.',
                'message_mail' => 'Le dossier de remise en circulation de votre vehicule est en cours d\'examen.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleReuseApproved' => [
                'name' => 'vehicle-reuse-approved',
                'title' => 'Demande approuvee',
                'message_sms' => 'La demande de remise en circulation de votre vehicule a ete approuvee.',
                'message_in_app' => 'La demande de remise en circulation de votre vehicule a ete approuvee.',
                'message_mail' => 'La demande de remise en circulation de votre vehicule a ete approuvee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleReuseRejected' => [
                'name' => 'vehicle-reuse-rejected',
                'title' => 'Demande rejetee',
                'message_sms' => 'La demande de remise en circulation de votre vehicule a ete rejetee.',
                'message_in_app' => 'La demande de remise en circulation de votre vehicule a ete rejetee.',
                'message_mail' => 'La demande de remise en circulation de votre vehicule a ete rejetee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleReusePaymentSuccessful' => [
                'name' => 'vehicle-reuse-payment-successful',
                'title' => 'Paiement reussi',
                'message_sms' => 'Le paiement pour la remise en circulation de votre vehicule a ete effectue avec succes.',
                'message_in_app' => 'Le paiement pour la remise en circulation de votre vehicule a ete effectue avec succes.',
                'message_mail' => 'Le paiement pour la remise en circulation de votre vehicule a ete effectue avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleReusePaymentError' => [
                'name' => 'vehicle-reuse-payment-error',
                'title' => 'Echec du paiement',
                'message_sms' => 'Le paiement pour la remise en circulation de votre vehicule a echoue. Veuillez reessayer.',
                'message_in_app' => 'Le paiement pour la remise en circulation de votre vehicule a echoue. Veuillez reessayer.',
                'message_mail' => 'Le paiement pour la remise en circulation de votre vehicule a echoue. Veuillez reessayer.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleReuseOngoing' => [
                'name' => 'vehicle-reuse-ongoing',
                'title' => 'Remise en circulation de vehicule en cours',
                'message_sms' => 'La remise en circulation de votre vehicule est en cours',
                'message_in_app' => 'La remise en circulation de votre vehicule est en cours',
                'message_mail' => 'La remise en circulation de votre vehicule est en cours',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleReuseSuccessful' => [
                'name' => 'vehicle-reuse-successful',
                'title' => 'Remise en circulation de vehicule effectuee avec succes',
                'message_sms' => 'La remise en circulation de votre vehicule a ete effectuee avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_in_app' => 'La remise en circulation de votre vehicule a ete effectuee avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_mail' => 'La remise en circulation de votre vehicule a ete effectuee avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleRegulatoryAuthorityServiceApplicationSubmittedSuccessfully' => [
                'name' => 'vehicle-regulatory-authority-service-application-submitted-successfully',
                'title' => 'Dossier soumis',
                'message_sms' => 'Votre dossier de souscription au service de l\'ANATT a ete soumis avec succes.',
                'message_in_app' => 'Votre dossier de souscription au service de l\'ANATT a ete soumis avec succes.',
                'message_mail' => 'Votre dossier de souscription au service de l\'ANATT a ete soumis avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleRegulatoryAuthorityServiceApplicationUnderReview' => [
                'name' => 'vehicle-regulatory-authority-service-application-under-review',
                'title' => 'Examen de dossier en cours',
                'message_sms' => 'Votre dossier de souscription au service de l\'ANATT est en cours d\'examen.',
                'message_in_app' => 'Votre dossier de souscription au service de l\'ANATT est en cours d\'examen.',
                'message_mail' => 'Votre dossier de souscription au service de l\'ANATT est en cours d\'examen.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleRegulatoryAuthorityServiceUsageApproved' => [
                'name' => 'vehicle-regulatory-authority-service-usage-approved',
                'title' => 'Demande approuvee',
                'message_sms' => 'Votre demande de souscription au service de l\'ANATT a ete approuvee.',
                'message_in_app' => 'Votre demande de souscription au service de l\'ANATT a ete approuvee.',
                'message_mail' => 'Votre demande de souscription au service de l\'ANATT a ete approuvee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleRegulatoryAuthorityServiceUsageRejected' => [
                'name' => 'vehicle-regulatory-authority-service-usage-rejected',
                'title' => 'Demande rejetee',
                'message_sms' => 'Votre demande de souscription au service de l\'ANATT a ete rejetee.',
                'message_in_app' => 'Votre demande de souscription au service de l\'ANATT a ete rejetee.',
                'message_mail' => 'Votre demande de souscription au service de l\'ANATT a ete rejetee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleRegulatoryAuthorityServicePaymentSuccessful' => [
                'name' => 'vehicle-regulatory-authority-service-payment-successful',
                'title' => 'Paiement reussi',
                'message_sms' => 'Le paiement pour votre souscription au service de l\'ANATT a ete effectue avec succes.',
                'message_in_app' => 'Le paiement pour votre souscription au service de l\'ANATT a ete effectue avec succes.',
                'message_mail' => 'Le paiement pour votre souscription au service de l\'ANATT a ete effectue avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleRegulatoryAuthorityServicePaymentError' => [
                'name' => 'vehicle-regulatory-authority-service-payment-error',
                'title' => 'Echec du paiement',
                'message_sms' => 'Le paiement pour votre souscription au service de l\'ANATT a echoue. Veuillez reessayer.',
                'message_in_app' => 'Le paiement pour votre souscription au service de l\'ANATT a echoue. Veuillez reessayer.',
                'message_mail' => 'Le paiement pour votre souscription au service de l\'ANATT a echoue. Veuillez reessayer.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'VehicleRegulatoryAuthorityServiceUsageSuccessful' => [
                'name' => 'vehicle-regulatory-authority-service-usage-successful',
                'title' => 'Service souscrit pris en compte',
                'message_sms' => 'Le service de l\'ANATT auquel vous avez souscrit a ete pris en compte.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_in_app' => 'Le service de l\'ANATT auquel vous avez souscrit a ete pris en compte.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_mail' => 'Le service de l\'ANATT auquel vous avez souscrit a ete pris en compte.\nVeuillez contacter l\'ANATT pour plus de details.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'InternationalVehiculeRegistrationDocumentIssuanceApplicationSubmittedSuccessfully' => [
                'name' => 'international-vehicule-registration-document-issuance-application-submitted-successfully',
                'title' => 'Dossier soumis',
                'message_sms' => 'Votre dossier d\'emission de carte grise internationale a ete soumis avec succes.',
                'message_in_app' => 'Votre dossier d\'emission de carte grise internationale a ete soumis avec succes.',
                'message_mail' => 'Votre dossier d\'emission de carte grise internationale a ete soumis avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'InternationalVehiculeRegistrationDocumentIssuanceApplicationUnderReview' => [
                'name' => 'international-vehicule-registration-document-issuance-application-under-review',
                'title' => 'Examen de dossier en cours',
                'message_sms' => 'Votre demande d\'emission de carte grise internationale est en cours d\'examen.',
                'message_in_app' => 'Votre demande d\'emission de carte grise internationale est en cours d\'examen.',
                'message_mail' => 'Votre demande d\'emission de carte grise internationale est en cours d\'examen.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'InternationalVehiculeRegistrationDocumentIssuanceApproved' => [
                'name' => 'international-vehicule-registration-document-issuance-approved',
                'title' => 'Demande approuvee',
                'message_sms' => 'Votre demande d\'emission de carte grise internationale a ete approuvee.',
                'message_in_app' => 'Votre demande d\'emission de carte grise internationale a ete approuvee.',
                'message_mail' => 'Votre demande d\'emission de carte grise internationale a ete approuvee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'InternationalVehiculeRegistrationDocumentIssuanceRejected' => [
                'name' => 'international-vehicule-registration-document-issuance-rejected',
                'title' => 'Demande rejetee',
                'message_sms' => 'Votre demande d\'emission de carte grise internationale a ete rejetee.',
                'message_in_app' => 'Votre demande d\'emission de carte grise internationale a ete rejetee.',
                'message_mail' => 'Votre demande d\'emission de carte grise internationale a ete rejetee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'InternationalVehiculeRegistrationDocumentIssuancePaymentSuccessful' => [
                'name' => 'international-vehicule-registration-document-issuance-payment-successful',
                'title' => 'Paiement reussi',
                'message_sms' => 'Le paiement pour l\'emission de carte grise internationale a ete effectue avec succes.',
                'message_in_app' => 'Le paiement pour l\'emission de carte grise internationale a ete effectue avec succes.',
                'message_mail' => 'Le paiement pour l\'emission de carte grise internationale a ete effectue avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'InternationalVehiculeRegistrationDocumentIssuancePaymentError' => [
                'name' => 'international-vehicule-registration-document-issuance-payment-error',
                'title' => 'Echec du paiement',
                'message_sms' => 'Le paiement pour l\'emission de carte grise internationale a echoue. Veuillez reessayer.',
                'message_in_app' => 'Le paiement pour l\'emission de carte grise internationale a echoue. Veuillez reessayer.',
                'message_mail' => 'Le paiement pour l\'emission de carte grise internationale a echoue. Veuillez reessayer.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'InternationalVehiculeRegistrationDocumentIssuanceOngoing' => [
                'name' => 'international-vehicule-registration-document-issuance-ongoing',
                'title' => 'Emission de carte grise internationale en cours',
                'message_sms' => 'Votre carte grise internationale est en cours d\'emission.',
                'message_in_app' => 'Votre carte grise internationale est en cours d\'emission.',
                'message_mail' => 'Votre carte grise internationale est en cours d\'emission.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'InternationalVehiculeRegistrationDocumentIssuanceSuccessful' => [
                'name' => 'international-vehicule-registration-document-issuance-successful',
                'title' => 'Carte grise internationale emise',
                'message_sms' => 'Votre carte grise internationale a ete emise.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_in_app' => 'Votre carte grise internationale a ete emise.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_mail' => 'Votre carte grise internationale a ete emise.\nVeuillez contacter l\'ANATT pour plus de details.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'InternationalVehiculeRegistrationDocumentExpired' => [
                'name' => 'international-vehicule-registration-document-expired',
                'title' => 'Expiration de carte grise internationale',
                'message_sms' => 'Votre carte grise internationale a expire. Veuillez contacter l\'ANATT pour son renouvellement.',
                'message_in_app' => 'Votre carte grise internationale a expire. Veuillez contacter l\'ANATT pour son renouvellement.',
                'message_mail' => 'Votre carte grise internationale a expire. Veuillez contacter l\'ANATT pour son renouvellement.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'TintedWindowsAuthorizationCardIssuanceApplicationSubmittedSuccessfully' => [
                'name' => 'tinted-windows-authorization-card-issuance-application-submitted-successfully',
                'title' => 'Dossier soumis',
                'message_sms' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees a ete soumise avec succes.',
                'message_in_app' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees a ete soumise avec succes.',
                'message_mail' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees a ete soumise avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'TintedWindowsAuthorizationCardIssuanceApplicationUnderReview' => [
                'name' => 'tinted-windows-authorization-card-issuance-application-under-review',
                'title' => 'Examen de dossier en cours',
                'message_sms' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees est en cours d\'examen.',
                'message_in_app' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees est en cours d\'examen.',
                'message_mail' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees est en cours d\'examen.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'TintedWindowsAuthorizationCardIssuanceApproved' => [
                'name' => 'tinted-windows-authorization-card-issuance-approved',
                'title' => 'Demande approuvee',
                'message_sms' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees a ete approuvee.',
                'message_in_app' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees a ete approuvee.',
                'message_mail' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees a ete approuvee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'TintedWindowsAuthorizationCardIssuanceRejected' => [
                'name' => 'tinted-windows-authorization-card-issuance-rejected',
                'title' => 'Demande rejetee',
                'message_sms' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees a ete rejetee.',
                'message_in_app' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees a ete Votre demande d\'emission de carte d\'authorisation de vitres teintees a ete.',
                'message_mail' => 'Votre demande d\'emission de carte d\'authorisation de vitres teintees a ete rejetee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'TintedWindowsAuthorizationCardIssuancePaymentSuccessful' => [
                'name' => 'tinted-windows-authorization-card-issuance-payment-successful',
                'title' => 'Paiement reussi',
                'message_sms' => 'Le paiement pour l\'emission de votre carte d\'authorisation de vitres teintees a ete effectue avec succes.',
                'message_in_app' => 'Le paiement pour l\'emission de votre carte d\'authorisation de vitres teintees a ete effectue avec succes.',
                'message_mail' => 'Le paiement pour l\'emission de votre carte d\'authorisation de vitres teintees a ete effectue avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'TintedWindowsAuthorizationCardIssuancePaymentError' => [
                'name' => 'tinted-windows-authorization-card-issuance-payment-error',
                'title' => 'Echec du paiement',
                'message_sms' => 'Le paiement pour l\'emission de votre carte d\'authorisation de vitres teintees a echoue. Veuillez reessayer.',
                'message_in_app' => 'Le paiement pour l\'emission de votre carte d\'authorisation de vitres teintees a echoue. Veuillez reessayer.',
                'message_mail' => 'Le paiement pour l\'emission de votre carte d\'authorisation de vitres teintees a echoue. Veuillez reessayer.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'TintedWindowsAuthorizationCardIssuanceOngoing' => [
                'name' => 'tinted-windows-authorization-card-issuance-ongoing',
                'title' => 'Emission de carte d\'authorisation de vitres teintees en cours',
                'message_sms' => 'L\'emission de votre carte d\'authorisation de vitres teintees est en cours.',
                'message_in_app' => 'L\'emission de votre carte d\'authorisation de vitres teintees est en cours.',
                'message_mail' => 'L\'emission de votre carte d\'authorisation de vitres teintees est en cours.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'TintedWindowsAuthorizationCardIssuanceSuccessful' => [
                'name' => 'tinted-windows-authorization-card-issuance-successful',
                'title' => 'Emission de carte d\'authorisation de vitres teintees effectuee avec succes',
                'message_sms' => 'Votre carte d\'authorisation de vitres teintees a ete emise.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_in_app' => 'Votre carte d\'authorisation de vitres teintees a ete emise.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_mail' => 'Votre carte d\'authorisation de vitres teintees a ete emise.\nVeuillez contacter l\'ANATT pour plus de details.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'TintedWindowsAuthorizationCardExpired' => [
                'name' => 'tinted-windows-authorization-card-expired',
                'title' => 'Expiration de carte d\'authorisation de vitres teintees',
                'message_sms' => 'Votre carte d\'authorisation de vitres teintees a expire. Veuillez contacter l\'ANATT pour son renouvellement.',
                'message_in_app' => 'Votre carte d\'authorisation de vitres teintees a expire. Veuillez contacter l\'ANATT pour son renouvellement.',
                'message_mail' => 'Votre carte d\'authorisation de vitres teintees a expire. Veuillez contacter l\'ANATT pour son renouvellement.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateShapeChangeApplicationSubmittedSuccessfully' => [
                'name' => 'plate-shape-change-application-submitted-successfully',
                'title' => 'Dossier soumis',
                'message_sms' => 'Votre dossier de changement de la forme de votre plaque d\'immatriculation a ete soumis avec succes.',
                'message_in_app' => 'Votre dossier de changement de la forme de votre plaque d\'immatriculation a ete soumis avec succes.',
                'message_mail' => 'Votre dossier de changement de la forme de votre plaque d\'immatriculation a ete soumis avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateShapeChangeApplicationUnderReview' => [
                'name' => 'plate-shape-change-application-under-review',
                'title' => 'Examen de dossier en cours',
                'message_sms' => 'Votre dossier de changement de la forme de votre plaque d\'immatriculation est en cours d\'examen.',
                'message_in_app' => 'Votre dossier de changement de la forme de votre plaque d\'immatriculation est en cours d\'examen.',
                'message_mail' => 'Votre dossier de changement de la forme de votre plaque d\'immatriculation est en cours d\'examen.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateShapeChangeApproved' => [
                'name' => 'plate-shape-change-approved',
                'title' => 'Demande approuvee',
                'message_sms' => 'Votre demande de changement de la forme de votre plaque d\'immatriculation a ete approuvee.',
                'message_in_app' => 'Votre demande de changement de la forme de votre plaque d\'immatriculation a ete approuvee.',
                'message_mail' => 'Votre demande de changement de la forme de votre plaque d\'immatriculation a ete approuvee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateShapeChangeRejected' => [
                'name' => 'plate-shape-change-rejected',
                'title' => 'Demande rejetee',
                'message_sms' => 'Votre demande de changement de la forme de votre plaque d\'immatriculation a ete rejetee.',
                'message_in_app' => 'Votre demande de changement de la forme de votre plaque d\'immatriculation a ete rejetee.',
                'message_mail' => 'Votre demande de changement de la forme de votre plaque d\'immatriculation a ete rejetee.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateShapeChangePaymentSuccessful' => [
                'name' => 'plate-shape-change-payment-successful',
                'title' => 'Paiement reussi',
                'message_sms' => 'Le paiement pour le changement de la forme de votre plaque d\'immatriculation a ete effectue avec succes.',
                'message_in_app' => 'Le paiement pour le changement de la forme de votre plaque d\'immatriculation a ete effectue avec succes.',
                'message_mail' => 'Le paiement pour le changement de la forme de votre plaque d\'immatriculation a ete effectue avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateShapeChangePaymentError' => [
                'name' => 'plate-shape-change-payment-error',
                'title' => 'Echec du paiement',
                'message_sms' => 'Le paiement pour le changement de la forme de votre plaque d\'immatriculation a echoue. Veuillez reessayer.',
                'message_in_app' => 'Le paiement pour le changement de la forme de votre plaque d\'immatriculation a echoue. Veuillez reessayer.',
                'message_mail' => 'Le paiement pour le changement de la forme de votre plaque d\'immatriculation a echoue. Veuillez reessayer.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateShapeChangeOngoing' => [
                'name' => 'plate-shape-change-ongoing',
                'title' => 'Changement de forme de plaque d\'immatriculation en cours',
                'message_sms' => 'Le changement de la forme de votre plaque d\'immatriculation est en cours.',
                'message_in_app' => 'Le changement de la forme de votre plaque d\'immatriculation est en cours.',
                'message_mail' => 'Le changement de la forme de votre plaque d\'immatriculation est en cours.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            'PlateShapeChangeSuccessful' => [
                'name' => 'plate-shape-change-successful',
                'title' => 'Changement de forme de plaque d\'immatriculation effectue avec succes',
                'message_sms' => 'Le changement de la forme de votre plaque d\'immatriculation a ete effectue avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_in_app' => 'Le changement de la forme de votre plaque d\'immatriculation a ete effectue avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'message_mail' => 'Le changement de la forme de votre plaque d\'immatriculation a ete effectue avec succes.\nVeuillez contacter l\'ANATT pour plus de details.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            [
                'name' => 'space-registration-validated',
                'title' => "Validation de la demande d'enregistrement d'affilie",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Felicitations. Votre demande d'enregistrement en tant qu'affilie a ete approuvee. Pour definir vos acces a la plateforme utilisez le lien suivant.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::REGISTRATION_SUCCESSFUL,
                'title' => 'Inscription reussie',
                "message_sms" => 'Felicitations, votre inscription a ete finalisee avec succes. Vous pouvez maintenant acceder a la plateforme avec votre NPI.',
                "message_in_app" => 'Felicitations, votre inscription a ete finalisee avec succes. Vous pouvez maintenant acceder a la plateforme avec votre NPI.',
                "message_mail" => 'Felicitations, votre inscription a ete finalisee avec succes. Vous pouvez maintenant acceder a la plateforme avec votre NPI et le code otp qui sera envoye sur votre numero de telephone.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::COMPANY_REGISTRATION_SUBMITTED,
                'title' => 'Inscription de {company_name} soumise avec succes',
                "message_sms" => 'Felicitations, l\'inscription de votre entreprise {company_name} a ete soumise avec succes. Vous serez notifie a la fin du traitement.',
                "message_in_app" => 'Felicitations, l\'inscription de votre entreprise {company_name} a ete soumise avec succes. Vous serez notifie a la fin du traitement.',
                "message_mail" => 'Felicitations, l\'inscription de votre entreprise {company_name} a ete soumise avec succes. Vous serez notifie a la fin du traitement.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::SPACE_MEMBER_INVITATION,
                'title' => "Invitation a rejoindre un espace sur SIMVEB",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Vous avez reçu une invitation a l'espace {space_name}. Veuillez vous inscrire/connecter pour acceder a cet espace.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::SPACE_ADMIN_INVITATION,
                'title' => "Invitation a administrer un espace sur SIMVEB",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Vous avez reçu une invitation a administrer l'entreprise {company_name} sur la plateforme. Veuillez vous inscrire/connecter pour acceder a cet espace.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::IMMATRICULATION_DEMAND_SUBMITTED,
                'title' => "Demande d'immatriculation soumise",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre demande d'immatriculation {reference} a ete soumise avec succes.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::IMMATRICULATION_DEMAND_VERIFIED,
                'title' => "Demande d'immatriculation verifie",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Vous avez reçu une invitation a l'espace d'un affilie. {reference}",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::IMMATRICULATION_DEMAND_VALIDATED,
                'title' => "Demande d'immatriculation validee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Vous avez reçu une invitation a l'espace d'un affilie. {reference}",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::IMMATRICULATION_DEMAND_REJECTED,
                'title' => "Demande d'immatriculation rejetee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Vous avez reçu une invitation a l'espace d'un affilie. {reference}",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::IMMATRICULATION_ASSIGNED_TO_SERVICE,
                'title' => "Demande d'immatriculation assigne au service",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Vous avez reçu une invitation a l'espace d'un affilie. {reference}",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::IMMATRICULATION_PRINT_ORDER_EMITTED,
                'title' => "Ordre d'impression emis",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => 'L\'ordre d\'impression de votre plaque et/ou carte grise a ete emis, veuillez vous rapprocher d\'un agree pour poursuivre le processus. Reference de l\'ordre {reference}',
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::IMMATRICULATION_ASSIGNED_TO_STAFF, //////////
                'title' => "Demande d'immatriculation assigne",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Vous avez reçu une invitation a l'espace d'un affilie. Reference de la demande : {reference}",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::DEMAND_PAID,
                'title' => "Demande payee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Bonjour nous avons reçu votre paiement avec succes. {reference}",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::SPACE_REGISTERED,
                'title' => "Enregistrement finalisee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Felicitations, votre inscription a ete finalisee avec succes. Vous pouvez maintenant acceder a votre espace avec le lien ci-dessous.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::IMPRESSION_OTP_SENT,
                'title' => "Code OTP d'impression envoye",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Le processus d'impression de votre plaque a debute, pour le poursuive veuillez donner le code OTP suivant a un imprimeur : {otp}",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::PLATE_ORDER_CONFIRMED,
                'title' => "Commande de plaque approuvee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre commande de plaque {reference} a ete approuvee, veuillez confirmer la reception des plaques.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::PLATE_ORDER_PAYMENT_PENDING,
                'title' => "Paiement de la commande de plaque en attente",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre commande de plaque {reference} a ete approuvee, pour la finaliser veuillez proceder au paiment sur votre espace.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::PLATE_ORDER_PAYMENT_SUCCESS,
                'title' => "Paiement de la commande de plaque reussi",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Succes du paiement de la commande de plaque {reference}.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [

                'name' => NotificationNames::IMPRESSION_FINISHED,
                'title' => "Impression terminee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "L'impression de la plaque de votre demande d'immatriculation {reference} a ete imprimee. Veuillez vous rapprochez de votre imprimeur.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::PLATE_DELIVERED,
                'title' => "Plaque delivree",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "La plaque de la demande d'immatriculation {reference} a ete remise.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::ANATT_VALIDATE_PLATE,
                'title' => "Plaque validee par l'ANATT",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "La plaque de la demande d'immatriculation {reference} a ete validee par l'ANATT lors du contôle.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::ANATT_REJECT_PLATE,
                'title' => "Plaque rejetee par l'ANATT",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "La plaque de la demande d'immatriculation {reference} a ete rejetee par l'ANATT lors du contôle.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::PASSWORD_RESET_REQUEST,
                'title' => "Demande de reinitialisation de mot de passe",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Veuillez utiliser le lien ci-dessous pour reinitialiser votre mot de passe.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::PASSWORD_RESET_SUCCESS,
                'title' => "Mot de passe reinitialise avec succes",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre mot de passe a ete reinitialise avec succes.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::IMPORT_HAS_ERRORS,
                'title' => "Erreurs lors de l'importation des donnes par Excel",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "L'import des donnes s'est effectue avec des erreurs au  niveau de quelques lignes du fichier importe. Veuillez trouver ci-joint un fichier excel de recapitulatif que vous pourriez corriger et importer.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::SALE_DECLARATION_SUBMITTED,
                'title' => 'Dossier soumis',
                'message_sms' => 'Votre dossier de declaration de cession de votre vehicule a ete soumis avec succes.',
                'message_in_app' => 'Votre dossier de declaration de cession de votre vehicule a ete soumis avec succes.',
                'message_mail' => 'Votre dossier de declaration de cession de votre vehicule a ete soumis avec succes.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 7,
            ],
            [
                'name' => NotificationNames::SALE_DECLARATION_VERIFIED,
                'title' => "Cession de vehicule verifie",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Le dossier de declaration de cession {reference} de votre vehicule a ete verifie.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::SALE_DECLARATION_VALIDATED,
                'title' => "Cession de vehicule validee par l'ANATT",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Le dossier de declaration de cession {reference} de votre vehicule a ete validee par l'ANATT.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::PRESTIGE_LABEL_IMMATRICULATION_VALIDATE,
                'title' => "Plaque validee par l'ANATT",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "La plaque de la demande d'immatriculation de prestige label {reference} a ete traite et validee par l'ANATT lors du contôle.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::OTP_VERIFICATION,
                'title' => "Verifier votre identite",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "{purpose}, veuillez renseigner le code {otp} valable pendant {time} minute(s).",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::DEMAND_OTP_VERIFICATION,
                'title' => "Verifier votre identite",
                "message_sms" => "{purpose}, veuillez renseigner le code {otp} valable pendant {time} minute(s).",
                "message_in_app" => "",
                "message_mail" => "{purpose}, veuillez renseigner le code {otp} valable pendant {time} minute(s).",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::DEMAND_VALIDATED,
                'title' => "Demande validee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre demande de : {entityName} reference : {reference}  du vehicule, chassis : {vin}, immatricule {immatriculation_Number} a ete traite et validee par l'ANATT.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::DEMAND_REJECTED,
                'title' => "Demande rejetee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre demande de {entityName} reference : {reference}  du vehicule, chassis : {vin},  a ete traite et rejete par l'ANATT pour la raison suivante: {reason}",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::ORDER_SUBMITTED,
                'title' => "Commande soumise",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre commande {reference} a ete payee et soumise avec succes. Veuillez trouver ci-joint la facture de la  transaction",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::DEMAND_ASSIGNED_TO_CENTER,
                'title' => "Une nouvelle Demande a ete assignee a votre centre",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre centre a reçu une nouvelle demande de {entityName} ref: {reference} a traiter. ",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::DEMAND_ASSIGNED_TO_SERVICE,
                'title' => "Une nouvelle Demande a ete assignee a votre service",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre service a reçu une nouvelle demande de {entityName} ref: {reference} a traiter. ",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::DEMAND_ASSIGNED_TO_STAFF,
                'title' => "Une nouvelle Demande vous a ete assignee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Vous avez reçu une nouvelle demande de {entityName} ref: {reference} a traiter. ",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::PLATE_PRINTED,
                'title' => "Vos plaques ont ete imprimees",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => 'Vos plaques ont ete imprimees, veuillez vous rapprocher de l\'agree pour les recuperer puis confirmer la reception. Reference de l\'ordre d\'impression: {reference}.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::GRAY_CARD_PRINTED,
                'title' => "Votre carte grise a ete imprimee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => 'Votre carte grise a ete imprimee, veuillez vous rapprocher de l\'agree pour les recuperer puis confirmer la reception. Reference de l\'ordre d\'impression: {reference}.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::PRINT_VALIDATED,
                'title' => "Impression de plaque validee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => 'L\'impression de vos plaques a ete validee. Observation: {observation}. Reference de la demande d\'immatriculation {reference}.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::PRINT_REJECTED,
                'title' => 'Impression rejetee',
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => 'L\'impression de vos plaques a ete rejete pour les raison suivantes: {observation}. Reference de l\'ordre d\'impression {reference}.',
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::SPACE_SUSPENSION_REQUEST_VALIDATED,
                'title' => "Demande de suspension d'espace validee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre demande de suspension de l'espace {space_name} a ete validee. Desormais l'espace n'est plus accessible.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::SPACE_SUSPENSION_REQUEST_REJECTED,
                'title' => "Demande de suspension d'espace rejetee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre demande de suspension de l'espace {space_name} a ete rejetee. Raison du rejet: {reason}",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::SPACE_SUSPENSION_LIFTING_REQUEST_VALIDATED,
                'title' => "Demande de levee de suspension d'espace validee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre demande de levee  de suspension de l'espace {space_name} a ete validee. L'espace est de nouveau accessible.",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
            [
                'name' => NotificationNames::SPACE_SUSPENSION_LIFTING_REQUEST_REJECTED,
                'title' => "Demande de levee de suspension d'espace rejetee",
                "message_sms" => "",
                "message_in_app" => "",
                "message_mail" => "Votre demande de levee  de suspension de l'espace {space_name} a ete rejetee. Raison du rejet: {reason}",
                'total_repetition_count' => 1,
                'frequency_in_days' => 0,
            ],
        ] + Duplicate::NOTIFICATION_CONFIGS;

        foreach ($notificationConfigs as $notificationConfig) {
            NotificationConfig::updateOrCreate(["name" => $notificationConfig['name']], $notificationConfig);
        }
    }
}
