<?php

namespace Ntech\UserPackage\Database\Seeders;

use App\Consts\Roles;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class RolesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $roles = [
            [
                "name" => Roles::ADMIN,
                "label" => "Administrateur",
                "editable" => false,
                "permissions" => [
                    "dashboard",
                    "browse-staff", "store-staff", "update-staff", "show-staff", "delete-staff",
                    "browse-activity-log",
                    "browse-plate-color", "store-plate-color", "update-plate-color", "show-plate-color", "delete-plate-color",
                    "browse-service", "show-service", "store-service", "update-service", "delete-service",
                    "browse-vehicle-characteristic-category", "show-vehicle-characteristic-category", "store-vehicle-characteristic-category", "update-vehicle-characteristic-category", "delete-vehicle-characteristic-category",
                    "update-vehicle-characteristic-category-field-name",
                    "browse-vehicle-characteristic", "show-vehicle-characteristic", "store-vehicle-characteristic", "update-vehicle-characteristic", "delete-vehicle-characteristic",
                    "browse-vehicle-category", "show-vehicle-category", "store-vehicle-category", "update-vehicle-category", "delete-vehicle-category",
                    "browse-document-type", "show-document-type", "store-document-type", "update-document-type", "delete-document-type",
                    "browse-required-document-type", "show-required-document-type", "store-required-document-type", "update-required-document-type", "delete-required-document-type",
                    "browse-owner-type", "show-owner-type", "store-owner-type", "update-owner-type", "delete-owner-type",
                    "browse-space-registration-request", "store-space-registration-request", "show-space-registration-request", "validate-space-registration-request", "reject-space-registration-request", "delete-space-registration-request",
                    "browse-space", "show-space", "update-space", "delete-space", 'browse-space-staff',
                    "browse-vehicle-type", "show-vehicle-type", "store-vehicle-type", "update-vehicle-type", "delete-vehicle-type",
                    "browse-reserved-plate-number", "show-reserved-plate-number", "store-reserved-plate-number", "update-reserved-plate-number", "delete-reserved-plate-number",
                    "browse-notification-config", "show-notification-config", "update-notification-config",
                    "browse-commission", "store-commission", "show-commission", "update-commission", "delete-commission",
                    "browse-vehicle-energy-source", "store-vehicle-energy-source", "show-vehicle-energy-source", "update-vehicle-energy-source", "delete-vehicle-energy-source",
                    "browse-vehicle-power", "store-vehicle-power", "show-vehicle-power", "update-vehicle-power", "delete-vehicle-power",
                    "browse-vehicle-brand", "store-vehicle-brand", "show-vehicle-brand", "update-vehicle-brand", "delete-vehicle-brand",
                    "browse-plate-shape", "store-plate-shape", "show-plate-shape", "update-plate-shape", "delete-plate-shape",
                    "browse-blacklist-person", "store-blacklist-person", "show-blacklist-person", "update-blacklist-person", "delete-blacklist-person",
                    "browse-service", "store-service", "show-service", "update-service", "delete-service",
                    "browse-service-type", "store-service-type", "show-service-type", "update-service-type", "delete-service-type",
                    "browse-client-type", "show-client-type", "store-client-type", "update-client-type", "delete-client-type",
                    "browse-geographical-area", "store-geographical-area", "show-geographical-area", "update-geographical-area", "delete-geographical-area",
                    "browse-tinted-windows-authorization", "store-tinted-windows-authorization", "show-tinted-windows-authorization", "update-tinted-windows-authorization", "delete-tinted-windows-authorization",
                    "browse-international-vehicle-registration-document", "store-international-vehicle-registration-document", "show-international-vehicle-registration-document", "update-international-vehicle-registration-document", "delete-international-vehicle-registration-document",
                    "browse-immatriculation-format", "store-immatriculation-format", "show-immatriculation-format", "update-immatriculation-format", "delete-immatriculation-format",
                    "browse-role", "store-role", "show-role", "update-role", "delete-role",
                    "browse-permission", "store-permission", "show-permission", "update-permission", "delete-permission",
                    "browse-im-demand", "store-im-demand", "show-im-demand", "update-im-demand", "delete-im-demand", "validate-im-demand", "pre-validate-im-demand", "verify-im-demand", "reject-im-demand",
                    "access-config",
                    'browse-meta-data', 'search-meta-data', 'update-meta-data',
                    "browse-card-duplicate", "store-card-duplicate", "show-card-duplicate", "update-card-duplicate", "delete-card-duplicate", "verify-card-duplicate", "validate-card-duplicate", "assign-to-staff-card-duplicate", "affect-to-service-card-duplicate", "emit-print-order-card-duplicate", "print-card-duplicate",
                    "browse-plate-duplicate", "store-plate-duplicate", "show-plate-duplicate", "update-plate-duplicate", "delete-plate-duplicate", "verify-plate-duplicate", "validate-plate-duplicate", "assign-to-staff-plate-duplicate", "affect-to-service-plate-duplicate", "emit-print-order-plate-duplicate", "print-plate-duplicate",
                    "browse-impression-demand", "show-impression-demand",
                    'browse-plate-order', 'show-plate-order', 'store-plate-order', 'validate-plate-order', 'reject-plate-order',
                    'browse-plate', 'show-plate', 'store-plate', 'stats-plate',
                    'control-anatt-im-demand',
                    'browse-immatriculation-demand-stats', 'browse-duplicate-demand-stats', 'browse-stats',
                    'browse-park', 'store-park', 'show-park', 'update-park', 'delete-park',
                    'browse-border', 'store-border', 'show-border', 'update-border', 'delete-border',
                    'browse-management-center-type', 'store-management-center-type', 'show-management-center-type', 'update-management-center-type', 'delete-management-center-type',
                    'browse-zone', 'store-zone', 'show-zone', 'update-zone', 'delete-zone',
                    'browse-town', 'store-town', 'show-town', 'update-town', 'delete-town',
                    'browse-district', 'store-district', 'show-district', 'update-district', 'delete-district',
                    'browse-village', 'store-village', 'show-village', 'update-village', 'delete-village',
                    'browse-management-center', 'store-management-center', 'show-management-center', 'update-management-center', 'delete-management-center',
                    'browse-institution-type', 'store-institution-type', 'show-institution-type', 'update-institution-type', 'delete-institution-type',
                    'browse-institution', 'store-institution', 'show-institution', 'update-institution', 'delete-institution',
                    'browse-declarant', 'store-declarant', 'show-declarant', 'update-declarant', 'delete-declarant',
                    'browse-vehicle-administrative-status', 'show-vehicle-administrative-status',
                    "browse-price", "store-price", "show-price", "update-price", "delete-price",
                    'browse-invitation', 'store-invitation', 'show-invitation',
                    "browse-alert-type", "store-alert-type", "show-alert-type", "update-alert-type", "delete-alert-type",
                    "browse-profile-type", "store-profile-type", "show-profile-type", "update-profile-type",
                    'browse-organization', 'store-organization', 'show-organization', 'update-organization', 'delete-organization',
                    "browse-number-template", "store-number-template", "show-number-template", "update-number-template", "delete-number-template",
                    "browse-title-reason", "create-title-reason", "store-title-reason", "show-title-reason", "update-title-reason", "delete-title-reason",
                    "browse-title-reason-type", "store-title-reason-type", "show-title-reason-type", "update-title-reason-type", "delete-title-reason-type",
                    'browse-order', 'show-order',
                    "browse-reimmatriculation-reason", "show-reimmatriculation-reason", "update-reimmatriculation-reason",
                    'browse-auction-sale-vehicle', 'store-auction-sale-vehicle', 'show-auction-sale-vehicle', 'update-auction-sale-vehicle', 'delete-auction-sale-vehicle',
                    'browse-auction-sale-declaration', 'store-auction-sale-declaration', 'show-auction-sale-declaration', 'update-auction-sale-declaration', 'delete-auction-sale-declaration',
                    'browse-reform-declaration', 'store-reform-declaration', 'show-reform-declaration', 'update-reform-declaration', 'delete-reform-declaration',
                    'browse-accreditation', 'store-accreditation', 'show-accreditation', 'update-accreditation', 'delete-accreditation', 'validate-accreditation', 'reject-accreditation',
                    "browse-gma-vehicle", "store-gma-vehicle", "import-gma-vehicle", "show-gma-vehicle", "update-gma-vehicle", "delete-gma-vehicle", "validate-gma-vehicle", "reject-gma-vehicle", "view-stats-gma-vehicle",
                    "browse-gmd-vehicle", "store-gmd-vehicle", "show-gmd-vehicle", "update-gmd-vehicle", "delete-gmd-vehicle", "import-gmd-vehicle", "validate-gmd-vehicle", "reject-gmd-vehicle",
                    "verify-imstd", "pre-validate-imstd", "validate-imstd", "reject-imstd", "print-imstd-plate", "print-imstd-gray-card",
                    "verify-rim", "pre-validate-rim", "validate-rim", "reject-rim", "print-rim-plate", "print-rim-gray-card",
                    "verify-impl", "pre-validate-impl", "validate-impl", "reject-impl", "print-impl-plate", "print-impl-gray-card",
                    "verify-impn", "pre-validate-impn", "validate-impn", "reject-impn", "print-impn-plate", "print-impn-gray-card",
                    "verify-impnl", "pre-validate-impnl", "validate-impnl", "reject-impnl", "print-impnl-plate", "print-impnl-gray-card",
                    "verify-dcvt", "pre-validate-dcvt", "validate-dcvt", "reject-dcvt",
                    "verify-mtn", "pre-validate-mtn", "validate-mtn", "reject-mtn", "print-mtn-gray-card",
                    "verify-vtf", "pre-validate-vtf", "validate-vtf", "reject-vtf", "close-vtf", "print-vtf-gray-card",
                    "verify-atvt", "pre-validate-atvt", "validate-atvt", "reject-atvt", "print-atvt-gray-card",
                    "verify-gdv", "pre-validate-gdv", "validate-gdv", "reject-gdv", "print-gdv-gray-card",
                    "verify-dptt", "pre-validate-dptt", "validate-dptt", "reject-dptt",
                    "verify-rptt", "pre-validate-rptt", "validate-rptt", "reject-rptt",
                    "verify-tfmp", "pre-validate-tfmp", "validate-tfmp", "reject-tfmp", "print-tfmp-plate",
                    "browse-action", "store-action", "show-action", "update-action", "delete-action",
                    "show-wallet", "update-wallet",
                    "verify-plate-duplicate", "pre-validate-plate-duplicate", "validate-plate-duplicate", "reject-plate-duplicate",
                    "browse-print-order", "show-print-order", "confirm-print-order-affectation",
                    'print-plate', 'print-gray-card', "validate-print",
                    "validate-reserved-plate-number",
                    "show-vehicle",
                    "browse-immatriculation-type", "store-immatriculation-type", "show-immatriculation-type", "update-immatriculation-type", "delete-immatriculation-type",
                    "browse-opposition", "create-opposition", "store-opposition", "update-opposition", "show-opposition", "delete-opposition", "validate-opposition-by-clerk", "validate-opposition-by-judge", "reject-opposition-by-clerk", "reject-opposition-by-judge", "lift-opposition",
                    'browse-space-suspension-request', 'show-space-suspension-request', 'store-space-suspension-request', 'update-space-suspension-request', 'validate-space-suspension-request',
                    'browse-space-suspension-lifting-request', 'show-space-suspension-lifting-request', 'store-space-suspension-lifting-request', 'update-space-suspension-lifting-request', 'validate-space-suspension-lifting-request',
                    "browse-motorcycle", "store-motorcycle", "show-motorcycle", "update-motorcycle", "delete-motorcycle",
                    "browse-transformation-type", "store-transformation-type", "show-transformation-type", "update-transformation-type", "delete-transformation-type",
                     "browse-staff", "store-staff", "update-staff", "show-staff", "delete-staff",
                     "browse-activity-log",
                     "browse-plate-color", "store-plate-color", "update-plate-color", "show-plate-color", "delete-plate-color",
                     "browse-service", "show-service", "store-service", "update-service", "delete-service",
                     "browse-vehicle-characteristic-category", "show-vehicle-characteristic-category", "store-vehicle-characteristic-category", "update-vehicle-characteristic-category", "delete-vehicle-characteristic-category",
                     "update-vehicle-characteristic-category-field-name",
                     "browse-vehicle-characteristic", "show-vehicle-characteristic", "store-vehicle-characteristic", "update-vehicle-characteristic", "delete-vehicle-characteristic",
                     "browse-vehicle-category", "show-vehicle-category", "store-vehicle-category", "update-vehicle-category", "delete-vehicle-category",
                     "browse-document-type", "show-document-type", "store-document-type", "update-document-type", "delete-document-type",
                     "browse-required-document-type", "show-required-document-type", "store-required-document-type", "update-required-document-type", "delete-required-document-type",
                     "browse-owner-type", "show-owner-type", "store-owner-type", "update-owner-type", "delete-owner-type",
                     "browse-space-registration-request", "store-space-registration-request", "show-space-registration-request", "validate-space-registration-request", "reject-space-registration-request", "delete-space-registration-request",
                     "browse-space", "show-space", "update-space", "delete-space", 'browse-space-staff',
                     "browse-vehicle-type", "show-vehicle-type", "store-vehicle-type", "update-vehicle-type", "delete-vehicle-type",
                     "browse-reserved-plate-number", "show-reserved-plate-number", "store-reserved-plate-number", "update-reserved-plate-number", "delete-reserved-plate-number",
                     "browse-notification-config", "show-notification-config", "update-notification-config",
                     "browse-commission", "store-commission", "show-commission", "update-commission", "delete-commission",
                     "browse-vehicle-energy-source", "store-vehicle-energy-source", "show-vehicle-energy-source", "update-vehicle-energy-source", "delete-vehicle-energy-source",
                     "browse-vehicle-power", "store-vehicle-power", "show-vehicle-power", "update-vehicle-power", "delete-vehicle-power",
                     "browse-vehicle-brand", "store-vehicle-brand", "show-vehicle-brand", "update-vehicle-brand", "delete-vehicle-brand",
                     "browse-plate-shape", "store-plate-shape", "show-plate-shape", "update-plate-shape", "delete-plate-shape",
                     "browse-blacklist-person", "store-blacklist-person", "show-blacklist-person", "update-blacklist-person", "delete-blacklist-person",
                     "browse-service", "store-service", "show-service", "update-service", "delete-service",
                     "browse-service-type", "store-service-type", "show-service-type", "update-service-type", "delete-service-type",
                     "browse-client-type", "show-client-type", "store-client-type", "update-client-type", "delete-client-type",
                     "browse-geographical-area", "store-geographical-area", "show-geographical-area", "update-geographical-area", "delete-geographical-area",
                     "browse-tinted-windows-authorization", "store-tinted-windows-authorization", "show-tinted-windows-authorization", "update-tinted-windows-authorization", "delete-tinted-windows-authorization",
                     "browse-international-vehicle-registration-document", "store-international-vehicle-registration-document", "show-international-vehicle-registration-document", "update-international-vehicle-registration-document", "delete-international-vehicle-registration-document",
                     "browse-immatriculation-format", "store-immatriculation-format", "show-immatriculation-format", "update-immatriculation-format", "delete-immatriculation-format",
                     "browse-role", "store-role", "show-role", "update-role", "delete-role",
                     "browse-permission", "store-permission", "show-permission", "update-permission", "delete-permission",
                     "browse-im-demand", "store-im-demand", "show-im-demand", "update-im-demand", "delete-im-demand", "validate-im-demand", "pre-validate-im-demand", "verify-im-demand", "reject-im-demand",
                     "access-config",
                     'browse-meta-data', 'search-meta-data', 'update-meta-data',
                     "browse-card-duplicate", "store-card-duplicate", "show-card-duplicate", "update-card-duplicate", "delete-card-duplicate", "verify-card-duplicate", "validate-card-duplicate", "assign-to-staff-card-duplicate", "affect-to-service-card-duplicate", "emit-print-order-card-duplicate", "print-card-duplicate",
                     "browse-plate-duplicate", "store-plate-duplicate", "show-plate-duplicate", "update-plate-duplicate", "delete-plate-duplicate", "verify-plate-duplicate", "validate-plate-duplicate", "assign-to-staff-plate-duplicate", "affect-to-service-plate-duplicate", "emit-print-order-plate-duplicate", "print-plate-duplicate",
                     "browse-impression-demand", "show-impression-demand",
                     'browse-plate-order', 'show-plate-order', 'store-plate-order', 'validate-plate-order', 'reject-plate-order',
                     'browse-plate', 'show-plate', 'store-plate', 'stats-plate',
                     'control-anatt-im-demand',
                     'browse-immatriculation-demand-stats', 'browse-duplicate-demand-stats', 'browse-stats',
                     'browse-park', 'store-park', 'show-park', 'update-park', 'delete-park',
                     'browse-border', 'store-border', 'show-border', 'update-border', 'delete-border',
                     'browse-management-center-type', 'store-management-center-type', 'show-management-center-type', 'update-management-center-type', 'delete-management-center-type',
                     'browse-zone', 'store-zone', 'show-zone', 'update-zone', 'delete-zone',
                     'browse-town', 'store-town', 'show-town', 'update-town', 'delete-town',
                     'browse-district', 'store-district', 'show-district', 'update-district', 'delete-district',
                     'browse-village', 'store-village', 'show-village', 'update-village', 'delete-village',
                     'browse-management-center', 'store-management-center', 'show-management-center', 'update-management-center', 'delete-management-center',
                     'browse-institution-type', 'store-institution-type', 'show-institution-type', 'update-institution-type', 'delete-institution-type',
                     'browse-institution', 'store-institution', 'show-institution', 'update-institution', 'delete-institution',
                     'browse-declarant', 'store-declarant', 'show-declarant', 'update-declarant', 'delete-declarant',
                     'browse-vehicle-administrative-status', 'show-vehicle-administrative-status',
                     "browse-price", "store-price", "show-price", "update-price", "delete-price",
                     'browse-invitation', 'store-invitation', 'show-invitation',
                     "browse-alert-type", "store-alert-type", "show-alert-type", "update-alert-type", "delete-alert-type",
                     "browse-profile-type", "store-profile-type", "show-profile-type", "update-profile-type",
                     'browse-organization', 'store-organization', 'show-organization', 'update-organization', 'delete-organization',
                     "browse-number-template", "store-number-template", "show-number-template", "update-number-template", "delete-number-template",
                     "browse-title-reason", "create-title-reason", "store-title-reason", "show-title-reason", "update-title-reason", "delete-title-reason",
                     "browse-title-reason-type", "store-title-reason-type", "show-title-reason-type", "update-title-reason-type", "delete-title-reason-type",
                     'browse-order', 'show-order',
                     "browse-reimmatriculation-reason", "show-reimmatriculation-reason", "update-reimmatriculation-reason",
                     'browse-auction-sale-vehicle', 'store-auction-sale-vehicle', 'show-auction-sale-vehicle', 'update-auction-sale-vehicle', 'delete-auction-sale-vehicle',
                     'browse-auction-sale-declaration', 'store-auction-sale-declaration', 'show-auction-sale-declaration', 'update-auction-sale-declaration', 'delete-auction-sale-declaration',
                     'browse-reform-declaration', 'store-reform-declaration', 'show-reform-declaration', 'update-reform-declaration', 'delete-reform-declaration',
                     'browse-accreditation', 'store-accreditation', 'show-accreditation', 'update-accreditation', 'delete-accreditation', 'validate-accreditation', 'reject-accreditation',
                     "browse-gma-vehicle", "store-gma-vehicle", "import-gma-vehicle", "show-gma-vehicle", "update-gma-vehicle", "delete-gma-vehicle", "validate-gma-vehicle", "reject-gma-vehicle", "view-stats-gma-vehicle",
                     "browse-gmd-vehicle", "store-gmd-vehicle", "show-gmd-vehicle", "update-gmd-vehicle", "delete-gmd-vehicle", "import-gmd-vehicle", "validate-gmd-vehicle",
                     "verify-imstd", "pre-validate-imstd", "validate-imstd", "reject-imstd", "print-imstd-plate", "print-imstd-gray-card",
                     "verify-rim", "pre-validate-rim", "validate-rim", "reject-rim", "print-rim-plate", "print-rim-gray-card",
                     "verify-impl", "pre-validate-impl", "validate-impl", "reject-impl", "print-impl-plate", "print-impl-gray-card",
                     "verify-impn", "pre-validate-impn", "validate-impn", "reject-impn", "print-impn-plate", "print-impn-gray-card",
                     "verify-impnl", "pre-validate-impnl", "validate-impnl", "reject-impnl", "print-impnl-plate", "print-impnl-gray-card",
                     "verify-dcvt", "pre-validate-dcvt", "validate-dcvt", "reject-dcvt",
                     "verify-mtn", "pre-validate-mtn", "validate-mtn", "reject-mtn", "print-mtn-gray-card",
                     "verify-atvt", "pre-validate-atvt", "validate-atvt", "reject-atvt", "print-atvt-gray-card",
                     "verify-dptt", "pre-validate-dptt", "validate-dptt", "reject-dptt",
                     "verify-rptt", "pre-validate-rptt", "validate-rptt", "reject-rptt",
                     "verify-tfmp", "pre-validate-tfmp", "validate-tfmp", "reject-tfmp", "print-tfmp-plate",
                     "browse-action", "store-action", "show-action", "update-action", "delete-action",
                     "show-wallet", "update-wallet",
                     "verify-plate-duplicate", "pre-validate-plate-duplicate", "validate-plate-duplicate", "reject-plate-duplicate",
                     "browse-pledge", "store-pledge-by-distributor", "store-pledge-by-bank", "update-pledge", "show-pledge", "delete-pledge", "validate-pledge-by-anatt", "validate-pledge-by-institution", "validate-pledge-by-justice", "reject-pledge-by-anatt", "reject-pledge-by-institution", "reject-pledge-by-justice", "lift-pledge",
                     "browse-pledge-lift", "show-pledge-lift", "update-pledge-lift", "delete-pledge-lift", "validate-pledge-lift-by-anatt", "validate-pledge-lift-by-justice", "reject-pledge-lift-by-justice", "reject-pledge-lift-by-anatt",
                     "validate-reserved-plate-number",
                     "show-vehicle",
                     "browse-immatriculation-type", "store-immatriculation-type", "show-immatriculation-type", "update-immatriculation-type", "delete-immatriculation-type",
                     "browse-opposition", "create-opposition", "store-opposition", "update-opposition", "show-opposition", "delete-opposition", "validate-opposition-by-clerk", "validate-opposition-by-judge", "reject-opposition-by-clerk", "reject-opposition-by-judge", "lift-opposition",
                     'browse-space-suspension-request', 'show-space-suspension-request', 'store-space-suspension-request', 'update-space-suspension-request', 'validate-space-suspension-request',
                     'browse-space-suspension-lifting-request', 'show-space-suspension-lifting-request', 'store-space-suspension-lifting-request', 'update-space-suspension-lifting-request', 'validate-space-suspension-lifting-request',
                     "browse-transformation-type", "store-transformation-type", "show-transformation-type", "update-transformation-type", "delete-transformation-type",
                     "assign-to-center", "assign-to-service", "assign-to-staff", "affect-to-interpol", "emit-print-order",
                     "close-demand",
                     "browse-payment-provider", "store-payment-provider", "update-payment-provider", "show-payment-provider", "delete-payment-provider",
                     'browse-auction-sale-vehicle', 'store-auction-sale-vehicle', 'show-auction-sale-vehicle', 'update-auction-sale-vehicle', 'delete-auction-sale-vehicle',
                     'browse-auction-sale-declaration', 'store-auction-sale-declaration', 'show-auction-sale-declaration', 'update-auction-sale-declaration', 'delete-auction-sale-declaration',
                     'browse-reform-declaration', 'store-reform-declaration', 'show-reform-declaration', 'update-reform-declaration', 'delete-reform-declaration',
                ]
            ],
            [
                'name' => Roles::AFFILIATE_ADMIN,
                "label" => "Affilié administrateur",
                "editable" => false,
                "permissions" => [
                    "dashboard",
                    "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                ],
            ],
            [
                'name' => Roles::INTERPOL,
                "label" => "Interpole",
                "editable" => false,
                "permissions" => [
                    "dashboard",
                    "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                     "interpol-validate-impn", "interpol-reject-impn",
                     "interpol-validate-rim", "interpol-reject-rim",
                     "interpol-validate-imstd", "interpol-reject-imstd",
                     "browse-blacklist-vehicle", "store-blacklist-vehicle", "show-blacklist-vehicle", "validate-blacklist-vehicle", "delete-blacklist-vehicle", "reject-blacklist-vehicle",
                ],
            ],
            [
                'name' => Roles::AFFILIATE_HEADER,
                "label" => "Affilié dirigeant",
                "editable" => false,
                "permissions" => [
                    "dashboard",
                     "browse-space-staff",
                     'browse-invitation', 'store-invitation', 'show-invitation',
                ],
            ],
            [
                'name' => Roles::AFFILIATE_MEMBER,
                "label" => "Affilié membre",
                "editable" => false,
                "permissions" => [
                    "dashboard",
                ],
            ],
            [
                'name' => Roles::SERVICE_HEADER,
                'label' => "Chef Service",
                'editable' => false,
                'permissions' => [
                    "dashboard",
                     "browse-im-demand", "store-im-demand", "show-im-demand", "update-im-demand", "delete-im-demand", "validate-im-demand", "pre-validate-im-demand", "verify-im-demand", "reject-im-demand", "interpol-validate-im-demand", "interpol-pre-validate-im-demand", "reject-interpol-im-demand",
                     "browse-card-duplicate", "store-card-duplicate", "show-card-duplicate", "update-card-duplicate", "delete-card-duplicate", "verify-card-duplicate", "validate-card-duplicate", "assign-to-staff-card-duplicate", "affect-to-service-card-duplicate", "emit-print-order-card-duplicate", "print-card-duplicate",
                     "browse-plate-duplicate", "store-plate-duplicate", "show-plate-duplicate", "update-plate-duplicate", "delete-plate-duplicate", "verify-plate-duplicate", "validate-plate-duplicate", "assign-to-staff-plate-duplicate", "affect-to-service-plate-duplicate", "emit-print-order-plate-duplicate", "print-plate-duplicate",

                ],
            ],
            [
                'name' => Roles::SERVICE_STAFF,
                'label' => "Staff de Service",
                'editable' => false,
                'permissions' => [
                    "dashboard",
                    "browse-im-demand", "store-im-demand", "show-im-demand", "update-im-demand", "delete-im-demand", "validate-im-demand", "pre-validate-im-demand", "verify-im-demand", "reject-im-demand",
                    "verify-imstd", "pre-validate-imstd", "validate-imstd", "reject-imstd",
                    "verify-rim", "pre-validate-rim", "validate-rim", "reject-rim",
                    "verify-impl", "pre-validate-impl", "validate-impl", "reject-impl",
                    "verify-impn", "pre-validate-impn", "validate-impn", "reject-impn",
                    "verify-impnl", "pre-validate-impnl", "validate-impnl", "reject-impnl",
                    "verify-dcvt", "pre-validate-dcvt", "validate-dcvt", "reject-dcvt",
                    "verify-mtn", "pre-validate-mtn", "validate-mtn", "reject-mtn",
                    "verify-vtf", "pre-validate-vtf", "validate-vtf", "reject-vtf", "close-vtf", "print-vtf-gray-card",
                    "verify-atvt", "pre-validate-atvt", "validate-atvt", "reject-atvt",
                    "verify-gdv", "pre-validate-gdv", "validate-gdv", "reject-gdv",
                    "verify-dptt", "pre-validate-dptt", "validate-dptt", "reject-dptt",
                    "verify-rptt", "pre-validate-rptt", "validate-rptt", "reject-rptt",
                    "verify-tfmp", "pre-validate-tfmp", "validate-tfmp", "reject-tfmp",
                    "browse-im-demand", "store-im-demand", "show-im-demand", "update-im-demand", "delete-im-demand", "validate-im-demand", "pre-validate-im-demand", "verify-im-demand", "reject-im-demand", "interpol-validate-im-demand", "interpol-pre-validate-im-demand", "reject-interpol-im-demand",
                    "browse-card-duplicate", "store-card-duplicate", "show-card-duplicate", "update-card-duplicate", "delete-card-duplicate", "verify-card-duplicate", "validate-card-duplicate", "assign-to-staff-card-duplicate", "affect-to-service-card-duplicate", "emit-print-order-card-duplicate", "print-card-duplicate",
                    "browse-plate-duplicate", "store-plate-duplicate", "show-plate-duplicate", "update-plate-duplicate", "delete-plate-duplicate", "verify-plate-duplicate", "validate-plate-duplicate", "assign-to-staff-plate-duplicate", "affect-to-service-plate-duplicate", "emit-print-order-plate-duplicate", "print-plate-duplicate",
                    "verify-plate-duplicate", "pre-validate-plate-duplicate", "validate-plate-duplicate", "reject-plate-duplicate",
                     "browse-im-demand", "store-im-demand", "show-im-demand", "update-im-demand", "delete-im-demand", "validate-im-demand", "pre-validate-im-demand", "verify-im-demand", "reject-im-demand",
                     "verify-imstd", "pre-validate-imstd", "validate-imstd", "reject-imstd",
                     "verify-rim", "pre-validate-rim", "validate-rim", "reject-rim",
                     "verify-impl", "pre-validate-impl", "validate-impl", "reject-impl",
                     "verify-impn", "pre-validate-impn", "validate-impn", "reject-impn",
                     "verify-impnl", "pre-validate-impnl", "validate-impnl", "reject-impnl",
                     "verify-dcvt", "pre-validate-dcvt", "validate-dcvt", "reject-dcvt",
                     "verify-mtn", "pre-validate-mtn", "validate-mtn", "reject-mtn",
                     "verify-atvt", "pre-validate-atvt", "validate-atvt", "reject-atvt",
                     "verify-dptt", "pre-validate-dptt", "validate-dptt", "reject-dptt",
                     "verify-rptt", "pre-validate-rptt", "validate-rptt", "reject-rptt",
                     "verify-tfmp", "pre-validate-tfmp", "validate-tfmp", "reject-tfmp",
                     "browse-im-demand", "store-im-demand", "show-im-demand", "update-im-demand", "delete-im-demand", "validate-im-demand", "pre-validate-im-demand", "verify-im-demand", "reject-im-demand", "interpol-validate-im-demand", "interpol-pre-validate-im-demand", "reject-interpol-im-demand",
                     "browse-card-duplicate", "store-card-duplicate", "show-card-duplicate", "update-card-duplicate", "delete-card-duplicate", "verify-card-duplicate", "validate-card-duplicate", "assign-to-staff-card-duplicate", "affect-to-service-card-duplicate", "emit-print-order-card-duplicate", "print-card-duplicate",
                     "browse-plate-duplicate", "store-plate-duplicate", "show-plate-duplicate", "update-plate-duplicate", "delete-plate-duplicate", "verify-plate-duplicate", "validate-plate-duplicate", "assign-to-staff-plate-duplicate", "affect-to-service-plate-duplicate", "emit-print-order-plate-duplicate", "print-plate-duplicate",
                     "verify-plate-duplicate", "pre-validate-plate-duplicate", "validate-plate-duplicate", "reject-plate-duplicate",
                ],
            ],
            [
                'name' => Roles::VEHICLE_OWNER,
                'label' => 'Propriétaire de véhicule',
                'editable' => false,
                'permissions' => [],
            ],
            [
                'name' => Roles::PRINTER,
                'label' => 'Imprimeur',
                'editable' => false,
                'permissions' => [
                     "browse-impression-demand", "show-impression-demand", "store-impression-demand", "validate-impression-demand", "reject-impression-demand", "confirm-impression-demand",
                     'browse-plate-order', 'show-plate-order', 'store-plate-order',
                     'browse-plate', 'show-plate', 'confirm-plate-reception', 'stats-plate',
                ],
            ],
            [
                'name' => Roles::CG_ADMIN,
                'label' => 'Admin Garage central',
                'editable' => false,
                'permissions' => [
                     "browse-gov-vehicle", "store-gov-vehicle", "import-gov-vehicle", "show-gov-vehicle", "update-gov-vehicle", "delete-gov-vehicle",
                     'browse-auction-sale-vehicle', 'store-auction-sale-vehicle', 'show-auction-sale-vehicle', 'update-auction-sale-vehicle', 'delete-auction-sale-vehicle',
                     'browse-auction-sale-declaration', 'store-auction-sale-declaration', 'show-auction-sale-declaration', 'update-auction-sale-declaration', 'delete-auction-sale-declaration',
                     'browse-reform-declaration', 'store-reform-declaration', 'show-reform-declaration', 'update-reform-declaration', 'delete-reform-declaration',
                     "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                ],
            ],
            [
                'name' => Roles::AUCTIONEER,
                'label' => 'Commissaire priseur',
                'editable' => false,
                'permissions' => [
                     'browse-auction-sale-vehicle', 'store-auction-sale-vehicle', 'show-auction-sale-vehicle', 'update-auction-sale-vehicle', 'delete-auction-sale-vehicle',
                     'browse-auction-sale-declaration', 'store-auction-sale-declaration', 'show-auction-sale-declaration', 'update-auction-sale-declaration', 'delete-auction-sale-declaration',
                     'browse-reform-declaration', 'store-reform-declaration', 'show-reform-declaration', 'update-reform-declaration', 'delete-reform-declaration',
                     "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",

                ],
            ],
            [
                'name' => Roles::GMA_ADMIN,
                'label' => 'Admin Garage matériel des affaires intérieurs',
                'editable' => false,
                'permissions' => [
                     "browse-gma-vehicle", "store-gma-vehicle", "import-gma-vehicle", "show-gma-vehicle", "update-gma-vehicle", "delete-gma-vehicle", "validate-gma-vehicle", "reject-gma-vehicle", "view-stats-gma-vehicle",
                     'browse-auction-sale-vehicle', 'store-auction-sale-vehicle', 'show-auction-sale-vehicle', 'update-auction-sale-vehicle', 'delete-auction-sale-vehicle',
                     'browse-auction-sale-declaration', 'store-auction-sale-declaration', 'show-auction-sale-declaration', 'update-auction-sale-declaration', 'delete-auction-sale-declaration',
                     'browse-reform-declaration', 'store-reform-declaration', 'show-reform-declaration', 'update-reform-declaration', 'delete-reform-declaration',
                     "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                ],
            ],
            [
                'name' => Roles::GMD_ADMIN,
                'label' => 'Admin Garage matériel de la diplomatie',
                'editable' => false,
                'permissions' => [
                     'browse-gmd-vehicle', 'store-gmd-vehicle', 'show-gmd-vehicle', 'update-gmd-vehicle', 'delete-gmd-vehicle', 'import-gmd-vehicle', 'validate-gmd-vehicle', "reject-gmd-vehicle",
                     "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                ],
            ],
            [
                'name' => Roles::POLICE_ADMIN,
                'label' => 'Admin de la police',
                'editable' => false,
                'permissions' => [
                     "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                     "browse-police-officer-assignment", "store-police-officer-assignment", "show-police-officer-assignment", "update-police-officer-assignment", "delete-police-officer-assignment", "validate-police-officer-assignment", "reject-police-officer-assignment",
                     "browse-vehicle-alert", "store-vehicle-alert", "show-vehicle-alert", "update-vehicle-alert", "delete-vehicle-alert",
                     "browse-vehicle-passage", "store-vehicle-passage", "show-vehicle-passage", "update-vehicle-passage", "delete-vehicle-passage",
                     "browse-blacklist-vehicle", "store-blacklist-vehicle", "show-blacklist-vehicle", "validate-blacklist-vehicle", "delete-blacklist-vehicle", "reject-blacklist-vehicle",
                ],
            ],
            [
                'name' => Roles::BANK,
                'label' => 'Banque',
                'editable' => false,
                'permissions' => [
                     "browse-pledge", "store-pledge-by-bank", "update-pledge", "show-pledge", "delete-pledge", "validate-pledge-by-institution", "reject-pledge-by-institution", "lift-pledge",
                     "browse-pledge-lift", "show-pledge-lift", "update-pledge-lift", "delete-pledge-lift",
                     "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",

                ],
            ],
            [
                'name' => Roles::CLERK,
                'label' => 'Greffier',
                'editable' => false,
                'permissions' => [
                     "browse-pledge", "show-pledge", "validate-pledge-by-justice", "reject-pledge-by-justice",
                     "browse-pledge-lift", "show-pledge-lift", "validate-pledge-lift-by-justice", "reject-pledge-lift-by-justice",
                     "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                    "browse-pledge", "show-pledge", "issue-pledge", "reject-pledge",
                    "browse-opposition", "create-opposition", "update-opposition", "show-opposition", "validate-opposition-by-clerk", "reject-opposition-by-clerk", "lift-opposition",
                    "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                ]
            ],
            [
                'name' => Roles::APPROVED_ADMIN,
                'label' => 'Admin Agréé',
                'editable' => false,
                'permissions' => [
                    "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                    "browse-print-order", "show-print-order", "confirm-print-order-affectation",
                    'browse-plate-order', 'show-plate-order', 'store-plate-order', 'validate-plate-order', 'reject-plate-order',
                    'print-plate', 'print-gray-card',
                    'show-wallet', 'update-wallet',
                    'browse-plate', 'show-plate', 'store-plate', 'stats-plate',
                ],
            ],
            [
                'name' => Roles::INVESTIGATING_JUDGE,
                'label' => "Juge d'instruction",
                'editable' => false,
                'permissions' => [
                     "browse-opposition", "create-opposition", "store-opposition", "update-opposition", "show-opposition", "delete-opposition", "validate-opposition-by-judge", "reject-opposition-by-judge",
                     "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                ]
            ],
            [
                'name' => Roles::COURT_ADMIN,
                'label' => "Tribunal admin",
                'editable' => false,
                'permissions' => [
                    // "browse-opposition", "create-opposition", "store-opposition", "update-opposition", "show-opposition", "delete-opposition",
                    "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                ]
            ],
            [
                'name' => Roles::DISTRIBUTOR,
                'label' => 'Concessionnaire',
                'editable' => false,
                'permissions' => [
                     "browse-pledge", "store-pledge-by-distributor", "update-pledge", "show-pledge", "delete-pledge",
                     "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff",
                ],
            ],
            [
                'name' => Roles::COMPANY_ADMIN,
                "label" => "Administrateur entreprise",
                "editable" => false,
                "permissions" => [
                    "browse-space-staff","store-space-staff","delete-space-staff","invite-space-staff","update-space-staff","deactivate-space-staff","show-space-staff","approve-cart",
                ],
            ],
            [
                'name' => Roles::COMPANY_MEMBER,
                "label" => "Membre entreprise",
                "editable" => false,
                "permissions" => [],
            ],
            [
                'name' => Roles::DEMAND_MANAGER,
                "label" => "Membre entreprise",
                "editable" => false,
                "permissions" => [
                    "assign-to-center", "assign-to-service", "assign-to-staff", "affect-to-interpol", "emit-print-order", "close-demand",
                    "browse-im-demand", "show-im-demand",
                    "browse-impression-demand", "show-impression-demand",
                    'control-anatt-im-demand',
                    'browse-immatriculation-demand-stats', 'browse-duplicate-demand-stats', 'browse-stats',
                ],
            ]
        ];

        foreach ($roles as $item) {
            $role = Role::query()->updateOrCreate(
                [
                    'name' => $item['name']
                ],
                [
                    'guard_name' => "api",
                    'name' => $item['name'],
                    'label' => $item['label'],
                    'editable' => $item['editable'],
                ]
            );
            $role->syncPermissions($item['permissions']);
        }
    }
}
